Repository IDEMSInternational/open-app-builder, pull requests merged in 2021-12, with the labels that each got.

#1108 Update version number to v0.12.3
  android/app/build.gradle
  package.json
Labels: Test - visual, Test - preview

#1077 Minor bug fix for template toggle button
  src/app/shared/components/template/components/toggle-bar/toggle-bar.scss
  src/app/shared/components/template/components/toggle-bar/toggle-bar.ts
Labels: Test - preview

#1126 add icons back into toggle bar
  src/app/shared/components/template/components/toggle-bar/toggle-bar.scss
Labels: Test - preview

#1139 add developer component docs
  documentation/docs/developers/adding-components.md
  documentation/mkdocs.yml
Labels: documentation

#1138 Feat/html component
  documentation/docs/components/html.md
  documentation/docs/components/images/html.png
  documentation/mkdocs.yml
  packages/app-data/data/template/template.component_demo.ts
  packages/data-models/flowTypes.ts
  src/app/shared/components/template/components/html/html.component.ts
  src/app/shared/components/template/components/index.ts
Labels: Test - preview

#1131 refactor/core-styles
  package.json
  src/app/app.component.html
  src/app/feature/notification/pages/notifications-debug/notifications-debug.page.html
  src/app/feature/notification/pages/notifications-debug/notifications-debug.page.ts
  src/app/feature/template/template.page.html
  src/app/feature/template/template.page.scss
  src/app/shared/components/template/components/button/button.component.html
  src/app/shared/components/template/components/button/button.component.scss
  src/app/shared/components/template/components/button/button.component.ts
  src/app/shared/components/template/components/combo-box/combo-box-modal/combo-box-modal.component.scss
  src/app/shared/components/template/components/combo-box/combo-box-modal/combo-box-modal.component.ts
  src/app/shared/components/template/components/combo-box/combo-box.component.ts
  src/app/shared/components/template/components/debugger.ts
  src/app/shared/components/template/components/image.ts
  src/app/shared/components/template/components/layout/accordion.scss
  src/app/shared/components/template/components/layout/animated_section.ts
  src/app/shared/components/template/components/layout/display_group.scss
  src/app/shared/components/template/components/layout/display_group.ts
  src/app/shared/components/template/components/layout/nav_group.ts
  src/app/shared/components/template/components/layout/popup.ts
  src/app/shared/components/template/components/radio-group/radio-group.component.scss
  src/app/shared/components/template/components/radio-group/radio-group.component.ts
  src/app/shared/components/template/components/round-icon-button/round-icon-button.component.ts
  src/app/shared/components/template/components/square-icon-button/square-icon-button.component.ts
  src/app/shared/components/template/components/subtitle.scss
  src/app/shared/components/template/components/subtitle.ts
  src/app/shared/components/template/components/text.ts
  src/app/shared/components/template/components/tile-component/tile-component.component.html
  src/app/shared/components/template/components/tile-component/tile-component.component.scss
  src/app/shared/components/template/components/tile-component/tile-component.component.ts
  src/app/shared/components/template/components/title.scss
  src/app/shared/components/template/components/title.ts
  src/app/shared/components/template/components/tmpl-components-common.scss
  src/app/shared/components/template/template-component.scss
  src/app/shared/components/template/template-component.ts
  src/app/shared/components/template/template-container.component.html
  src/app/shared/components/template/template-container.component.scss
  src/global.scss
  src/theme/_layout.scss
  src/theme/deployment/_components.scss
  src/theme/deployment/_overrides.scss
  src/theme/deployment/_templates.scss
  src/theme/deployment/_variables.scss
  src/theme/deployment/components/_display-group.scss
  src/theme/deployment/components/_image.scss
  src/theme/deployment/components/_index.scss
  src/theme/deployment/components/_modal.scss
  src/theme/deployment/components/_radio_group.scss
  src/theme/deployment/deployment.scss
  src/theme/deployment/templates/_home_screen.scss
  src/theme/deployment/templates/_index.scss
  src/theme/mixins.scss
  src/theme/variables.scss
  yarn.lock
Labels: Test - visual, Test - preview

#1144 update radio params docs
  documentation/docs/authors/template-component-parameter-list.md
Labels: documentation

#1142 Core style refactor fixes
  src/app/shared/components/template/components/audio/audio.component.scss
  src/app/shared/components/template/components/dashed-box/dashed-box.component.scss
  src/app/shared/components/template/components/layout/display_group.ts
  src/app/shared/components/template/components/tile-component/tile-component.component.scss
  src/app/shared/components/template/template-component.scss
  src/theme/deployment/_components.scss
  src/theme/deployment/_templates.scss
  src/theme/deployment/components/_display-group.scss
Labels: Test - visual, Test - preview
