Repository IDEMSInternational/open-app-builder, pull requests merged in 2022-07, with the labels that each got.

#1451 bug: fixed issue where text was not copied to clipboard on Android
  package.json
  src/app/shared/components/template/components/select-text/select-text.component.ts
  yarn.lock
Labels: Test - appetize

#1453 Deployment dev/plh tz
  android/app/build.gradle
  package.json
  src/app/shared/components/template/components/select-text/select-text.component.ts
  yarn.lock
Labels: Test - preview, Test - appetize

#1454 Deployment dev/plh za
  android/app/build.gradle
  package.json
  src/app/shared/components/template/components/select-text/select-text.component.ts
  yarn.lock
Labels: Test - preview, Test - appetize

#1439 refactor: begin system to define colour variables from theme colours
  src/app/app.component.ts
  src/app/feature/notification/pages/notifications-debug/notifications-debug.page.scss
  src/app/feature/theme/built-in-themes.ts
  src/app/feature/theme/theme-service/theme.service.ts
  src/theme/themes/default.scss
  src/theme/themes/utils/_index.scss
  src/theme/themes/utils/contrast-colour.scss
  src/theme/themes/utils/generate-theme.scss
  src/theme/variables.scss
Labels: Test - visual, Test - preview
