Repository IDEMSInternational/open-app-builder, pull requests merged in 2022-04, with the labels that each got.

#1312 Perf/home page
  android/app/src/main/assets/capacitor.config.json
  angular.json
  capacitor.config.ts
  package.json
  src/app/app.component.ts
  src/app/feature/survey/components/surveyJS-modal.component.scss
  src/app/feature/survey/components/surveyJS-modal.component.ts
  src/app/feature/survey/survey.module.ts
  src/app/feature/survey/survey.service.ts
  src/app/feature/survey/surveys/index.ts
  src/app/feature/survey/surveys/intro-splash.survey.ts
  src/app/feature/survey/surveys/welcome.survey.ts
  src/app/feature/survey/types/survey.types.ts
  yarn.lock
Labels: Test - visual, Test - preview, Test - appetize

#1313 feat: add crashlytics, custom error handler, perf monitor
  .github/workflows/android-build.yml
  .github/workflows/android-release.yml
  .github/workflows/test-appetize.yml
  android/app/build.gradle
  android/app/capacitor.build.gradle
  android/app/src/main/assets/capacitor.plugins.json
  android/build.gradle
  android/capacitor.settings.gradle
  package.json
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/shared/services/crashlytics/crashlytics.service.spec.ts
  src/app/shared/services/crashlytics/crashlytics.service.ts
  src/app/shared/services/error-handler/error-handler.service.spec.ts
  src/app/shared/services/error-handler/error-handler.service.ts
  src/app/shared/services/performance-monitor/performance-monitor.service.spec.ts
  src/app/shared/services/performance-monitor/performance-monitor.service.ts
  yarn.lock
Labels: Test - appetize

#1333 Chore/remove deprecated types
  package.json
  packages/app-data/data/care_package_list/care_package_list.ts
  packages/app-data/data/care_package_list/index.ts
  packages/app-data/data/completion_list/completion_list.ts
  packages/app-data/data/completion_list/index.ts
  packages/app-data/data/component_defaults/component_defaults.ts
  packages/app-data/data/component_defaults/index.ts
  packages/app-data/data/conversation/conversation.ts
  packages/app-data/data/conversation/index.ts
  packages/app-data/data/goal_list/goal_list.ts
  packages/app-data/data/goal_list/index.ts
  packages/app-data/data/habit_ideas/habit_ideas.ts
  packages/app-data/data/habit_ideas/index.ts
  packages/app-data/data/habit_list/habit_list.ts
  packages/app-data/data/habit_list/index.ts
  packages/app-data/data/home_page/home_page.ts
  packages/app-data/data/home_page/index.ts
  packages/app-data/data/module_list/index.ts
  packages/app-data/data/module_list/module_list.ts
  packages/app-data/data/module_page/index.ts
  packages/app-data/data/module_page/module_page.ts
  packages/app-data/data/task_list/index.ts
  packages/app-data/data/task_list/task_list.ts
  packages/app-data/data/tips/index.ts
  packages/app-data/data/tips/tips.ts
  packages/app-data/index.ts
  packages/data-models/flowTypes.ts
  packages/data-models/index.ts
  packages/data-models/package.json
  packages/data-models/tips.model.ts
  packages/scripts/src/commands/app-data/convert/index.ts
  packages/scripts/src/commands/app-data/convert/parsers/conversation/conversation.parser.ts
  packages/scripts/src/commands/app-data/convert/parsers/index.ts
  packages/scripts/src/commands/app-data/convert/parsers/task_list/task_list.parser.ts
  src/app/shared/services/data/data.service.ts
  src/app/shared/services/userMeta/userMeta.service.ts
  yarn.lock
Labels: Test - visual, Test - preview

#1330 refactor: plh intro splash
  .idems_app/deployments/plh/default.config.ts
  packages/data-models/constants.ts
  src/app/app.component.ts
  src/app/feature/survey/survey.module.ts
  src/app/feature/survey/surveys/index.ts
  src/app/feature/survey/surveys/plh-intro-splash.survey.ts
Labels: Test - preview

#1329 chore: remove google font imports
  src/app/shared/components/template/components/button/button.component.scss
  src/app/shared/components/template/components/layout/form.ts
  src/assets/fonts/README.md
  src/assets/fonts/roboto-v29-latin-300.woff
  src/assets/fonts/roboto-v29-latin-300.woff2
  src/assets/fonts/roboto-v29-latin-500.woff
  src/assets/fonts/roboto-v29-latin-500.woff2
  src/assets/fonts/roboto-v29-latin-700.woff
  src/assets/fonts/roboto-v29-latin-700.woff2
  src/assets/fonts/roboto-v29-latin-900.woff
  src/assets/fonts/roboto-v29-latin-900.woff2
  src/assets/fonts/roboto-v29-latin-italic.woff
  src/assets/fonts/roboto-v29-latin-italic.woff2
  src/assets/fonts/roboto-v29-latin-regular.woff
  src/assets/fonts/roboto-v29-latin-regular.woff2
  src/global.scss
  src/index.html
  src/theme/_fonts.scss
Labels: Test - visual, Test - preview

#1285 Added round button component documentation
  documentation/docs/components/images/round_button.png
  documentation/docs/components/round_button.md
  documentation/mkdocs.yml
Labels: documentation

#1327 Feat/latex component and pipe
  angular.json
  package.json
  packages/data-models/flowTypes.ts
  src/app/shared/components/template/components/index.ts
  src/app/shared/components/template/components/latex/latex.component.ts
  src/app/shared/components/template/pipes/index.ts
  src/app/shared/components/template/pipes/latex.pipe.ts
  yarn.lock
Labels: Test - preview

#1348 fix: strip bold markdown from notifications
  src/app/feature/campaign/campaign.service.ts
  src/app/feature/campaign/pages/campaign-debug/components/campaign-debug-row.ts
Labels: Test - preview

#1352 chore: remove first open fields
  src/app/app.component.ts
Labels: Test - preview
