Repository IDEMSInternational/open-app-builder, pull requests merged in 2022-05, with the labels that each got.

#1363 Content update 04/05/2022
  packages/app-data/sheets/data_list/debug/efm_act_list.json
  packages/app-data/sheets/data_list/debug/efm_chapter_list.json
  packages/app-data/sheets/global/app_menu_globals.json
  packages/app-data/sheets/global/localised_names.json
  packages/app-data/sheets/global/localised_names_tz.json
  packages/app-data/sheets/global/localised_names_za.json
  packages/app-data/sheets/global/names_of_characters.json
  packages/app-data/sheets/index.ts
  packages/app-data/sheets/template/app_menu_enter_dev_mode.json
  packages/app-data/sheets/template/app_menu_exit_dev_mode.json
  packages/app-data/sheets/template/box_video.json
  packages/app-data/sheets/template/component_demo/comp_animated_slides.json
  packages/app-data/sheets/template/component_demo/comp_animated_slides_fullscreen.json
  packages/app-data/sheets/template/debug/debug_emit_force.json
  packages/app-data/sheets/template/debug/debug_nesting_conditional.json
  packages/app-data/sheets/template/debug/efm_activity_template.json
  packages/app-data/sheets/template/debug/efm_chapter_acts_1.json
  packages/app-data/sheets/template/debug/efm_chapter_acts_2.json
  packages/app-data/sheets/template/debug/efm_chapters.json
  packages/app-data/sheets/template/debug/example_pop_ups.json
  packages/app-data/sheets/template/ending.json
  packages/app-data/sheets/template/lets_slow_down_lyrics.json
  packages/app-data/sheets/template/splash_screens.json
  packages/app-data/sheets/template/w_self_care_relax.json
Labels: Test - preview

#1326 Added text component documentation
  documentation/docs/components/images/text.png
  documentation/docs/components/text.md
  documentation/mkdocs.yml
Labels: documentation

#1357 feat: add support for full screen popups
  packages/app-data/sheets/template/debug/example_analytics.json
  packages/data-models/flowTypes.ts
  packages/scripts/src/commands/app-data/convert/utils/app-data-action.utils.ts
  packages/scripts/src/commands/app-data/convert/utils/app-data-string.utils.ts
  src/app/shared/components/template/services/instance/template-action.service.ts
Labels: Test - preview

#1379 Update EFM web-preview 17/05/2022
  .gitattributes
  .gitignore
  .idems_app/deployments/plh/global.config.ts
  angular.json
  documentation/docs/components/images/text.png
  documentation/docs/components/text.md
  documentation/docs/index.md
  documentation/mkdocs.yml
  packages/app-data/sheets/data_list/A_Very_Tall_Man_pages.json
  packages/app-data/sheets/data_list/Is_There_Anyone_Like_Me_data.json
  packages/app-data/sheets/template/efm_activity_body_template.json
  packages/app-data/sheets/template/efm_activity_template.json
  packages/app-data/sheets/template/efm_chapter_acts.json
  packages/data-models/flowTypes.ts
  packages/scripts/jasmine.json
  packages/scripts/src/commands/app-data/convert/utils/app-data-action.utils.ts
  packages/scripts/src/commands/app-data/convert/utils/app-data-string.utils.ts
  packages/server/docker/config/analytics_dashboard/matomo_config/.gitignore
  packages/test-e2e/projects/example/fixtures/profile.json
  packages/test-e2e/projects/example/fixtures/users.json
  packages/test-e2e/projects/example/integration/1-getting-started/todo.spec.js
  packages/test-e2e/projects/example/integration/2-advanced-examples/actions.spec.js
  packages/test-e2e/projects/example/integration/2-advanced-examples/aliasing.spec.js
  packages/test-e2e/projects/example/integration/2-advanced-examples/assertions.spec.js
  packages/test-e2e/projects/example/integration/2-advanced-examples/connectors.spec.js
  packages/test-e2e/projects/example/integration/2-advanced-examples/cookies.spec.js
  packages/test-e2e/projects/example/integration/2-advanced-examples/cypress_api.spec.js
  packages/test-e2e/projects/example/integration/2-advanced-examples/files.spec.js
  packages/test-e2e/projects/example/integration/2-advanced-examples/local_storage.spec.js
  packages/test-e2e/projects/example/integration/2-advanced-examples/location.spec.js
  packages/test-e2e/projects/example/integration/2-advanced-examples/misc.spec.js
  packages/test-e2e/projects/example/integration/2-advanced-examples/navigation.spec.js
  packages/test-e2e/projects/example/integration/2-advanced-examples/network_requests.spec.js
  packages/test-e2e/projects/example/integration/2-advanced-examples/querying.spec.js
  packages/test-e2e/projects/example/integration/2-advanced-examples/spies_stubs_clocks.spec.js
  packages/test-e2e/projects/example/integration/2-advanced-examples/traversal.spec.js
  packages/test-e2e/projects/example/integration/2-advanced-examples/utilities.spec.js
  packages/test-e2e/projects/example/integration/2-advanced-examples/viewport.spec.js
  packages/test-e2e/projects/example/integration/2-advanced-examples/waiting.spec.js
  packages/test-e2e/projects/example/integration/2-advanced-examples/window.spec.js
  packages/test-e2e/projects/example/plugins/index.js
  packages/test-e2e/projects/example/support/index.js
  packages/test-e2e/projects/plh/plugins/index.js
  packages/translations/examples/compiled/jsons/global.json
  packages/translations/examples/compiled/jsons/input_tour.json
  packages/translations/examples/compiled/jsons/template.json
  packages/translations/examples/compiled/strings/_combined.json
  packages/translations/examples/compiled/strings/esp.json
  packages/translations/examples/extracted/example_extracted.json
  packages/translations/examples/source/global.json
  packages/translations/examples/source/input_tour.json
  packages/translations/examples/source/template.json
  packages/translations/examples/translations/translated.esp.json
  src/app/app.component.ts
  src/app/feature/campaign/campaign.service.ts
  src/app/feature/campaign/pages/campaign-debug/components/campaign-debug-row.ts
  src/app/shared/components/template/services/instance/README.md
  src/app/shared/components/template/services/instance/template-action.service.ts
  src/assets/fonts/README.md
  tsconfig.app.json
Labels: Test - visual, Test - preview, Test - appetize

#1367 feat: add error message if tech support request doesn't sync immediately
  packages/data-models/app-config/globals.ts
  packages/data-models/app-config/index.ts
  packages/data-models/app-config/templates/README.md
  packages/data-models/app-config/templates/app_menu_privacy_policy.json
  packages/data-models/app-config/templates/feature_feedback_default.json
  packages/data-models/app-config/templates/feature_feedback_text_select.json
  packages/data-models/constants.ts
  src/app/feature/feedback/feedback.service.ts
  src/app/shared/services/db/db-sync.service.ts
Labels: Test - preview

#1351 feat: convert splash screens to templates
  .idems_app/deployments/plh/global.config.ts
  packages/data-models/constants.ts
  packages/data-models/flowTypes.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/feature/survey/survey.module.ts
  src/app/feature/survey/survey.service.ts
  src/app/feature/survey/surveys/index.ts
  src/app/feature/survey/surveys/plh-intro-splash.survey.ts
  src/app/feature/survey/types/survey.types.ts
  src/app/shared/components/template/components/animated-slides/animated-slides.component.html
  src/app/shared/components/template/components/animated-slides/animated-slides.component.scss
  src/app/shared/components/template/components/animated-slides/animated-slides.component.ts
  src/app/shared/components/template/components/index.ts
  src/theme/deployment/components/_display-group.scss
Labels: Test - preview

#1392 Include caregiver testimonials
  packages/app-data/assets/global/plh_audio/testimonials/caregiver/caregiver_test_w_1on1.mp3
  packages/app-data/assets/global/plh_audio/testimonials/caregiver/caregiver_test_w_consequence.mp3
  packages/app-data/assets/global/plh_audio/testimonials/caregiver/caregiver_test_w_crisis.mp3
  packages/app-data/assets/global/plh_audio/testimonials/caregiver/caregiver_test_w_instruct.mp3
  packages/app-data/assets/global/plh_audio/testimonials/caregiver/caregiver_test_w_money.mp3
  packages/app-data/assets/global/plh_audio/testimonials/caregiver/caregiver_test_w_praise.mp3
  packages/app-data/assets/global/plh_audio/testimonials/caregiver/caregiver_test_w_rules.mp3
  packages/app-data/assets/global/plh_audio/testimonials/caregiver/caregiver_test_w_safe.mp3
  packages/app-data/assets/global/plh_audio/testimonials/caregiver/caregiver_test_w_self_care.mp3
  packages/app-data/assets/global/plh_audio/testimonials/caregiver/caregiver_test_w_solve.mp3
  packages/app-data/assets/global/plh_audio/testimonials/caregiver/caregiver_test_w_stress.mp3
  packages/app-data/assets/global/plh_audio/testimonies/teen/w_1on1.mp3
  packages/app-data/assets/global/plh_audio/testimonies/teen/w_rules.mp3
  packages/app-data/assets/index.ts
  packages/app-data/sheets/data_list/workshop_data_list.json
  packages/app-data/sheets/template/home_practice.json
Labels: content
