Repository IDEMSInternational/open-app-builder, pull requests merged in 2023-02, with the labels that each got.

#1766 fix: dynamic item nested names
  packages/app-data/sheets/data_list/number_data.json
  packages/app-data/sheets/template/debug/debug_teen_ages.json
  packages/app-data/sheets/template/demographics_teen_age.json
  src/app/shared/components/template/processors/item.ts
  src/app/shared/components/template/services/instance/template-action.service.ts
  src/app/shared/components/template/services/template-variables.service.ts
Labels: test - preview

#1762 Deployment dev/plh tz
  .github/workflows/android-build.yml
  .github/workflows/android-release.yml
  .github/workflows/deployment-hosting.yml
  .github/workflows/deprecated/build-and-upload.yml
  .github/workflows/deprecated/pr-build.yml
  .github/workflows/sourcemaps-upload.yml
  .github/workflows/test-appetize.yml
  .github/workflows/test-build.yml
  .github/workflows/test-preview.yml
  .github/workflows/test-visual-compare.yml
  .github/workflows/test-visual-generate.yml
  README.md
  android/app/build.gradle
  documentation/docs/authors/local-sheets.md
  documentation/docs/developers/deployments.md
  documentation/docs/generated/index.html
  documentation/docs/generated/js/search/search_index.js
  documentation/docs/index.md
  package.json
  packages/app-data/sheets/data_list/funders_data_list.json
  packages/app-data/sheets/data_list/number_data.json
  packages/app-data/sheets/template/app_menu_reset_app_pop.json
  packages/app-data/sheets/template/app_menu_settings.json
  packages/app-data/sheets/template/demo_navigation.json
  packages/app-data/sheets/template/demographics_teen_age.json
  packages/app-data/translations/tz_sw/strings.json
  packages/app-data/translations_source/from_translators/translated.tz_sw.json
  packages/data-models/deployment.model.ts
  packages/data-models/workflows/deployment.workflows.ts
  packages/data-models/workflows/index.ts
  packages/data-models/workflows/workflow.model.ts
  packages/scripts/src/commands/deployment/get.ts
  packages/scripts/src/commands/deployment/set.ts
  packages/scripts/src/commands/workflow/index.ts
  packages/scripts/src/commands/workflow/run.ts
  packages/scripts/src/tasks/index.ts
  packages/scripts/src/tasks/providers/deployment.ts
  src/app/shared/components/template/processors/item.ts
  src/app/shared/components/template/services/instance/template-action.service.ts
  src/app/shared/components/template/services/template-variables.service.ts
  yarn.lock
Labels: test - preview

#1763 Feat/deployment creation
  .idems_app/.gitignore
  .idems_app/deployments/early_family_math/.gitignore
  .idems_app/deployments/early_family_math/config.ts
  .idems_app/deployments/local/.gitignore
  .idems_app/deployments/local/config.ts
  .idems_app/deployments/local/sheets/.gitignore
  .idems_app/deployments/perinatal/.gitignore
  .idems_app/deployments/perinatal/config.ts
  .idems_app/deployments/plh/.gitignore
  .idems_app/deployments/plh/config.ts
  .idems_app/deployments/plh/debug.config.ts
  .idems_app/deployments/plh/global.config.ts
  .idems_app/deployments/plh_debug/.gitignore
  .idems_app/deployments/plh_debug/config.ts
  .idems_app/deployments/plh_global/.gitignore
  .idems_app/deployments/plh_global/config.ts
  .idems_app/deployments/plh_tz/.gitignore
  .idems_app/deployments/plh_tz/config.ts
  .idems_app/deployments/plh_za/.gitignore
  .idems_app/deployments/plh_za/config.ts
  .idems_app/deployments/wash/.gitignore
  documentation/docs/developers/deployments.md
  documentation/docs/index.md
  package.json
  packages/@idemsInternational/gdrive-tools/package.json
  packages/api/package.json
  packages/data-models/deployment.model.ts
  packages/data-models/workflows/deployment.workflows.ts
  packages/dexie-sync/package.json
  packages/scripts/package.json
  packages/scripts/src/commands/app-data/copy.spec.ts
  packages/scripts/src/commands/compile/index.ts
  packages/scripts/src/commands/config/index.ts
  packages/scripts/src/commands/deployment/common.ts
  packages/scripts/src/commands/deployment/compile.ts
  packages/scripts/src/commands/deployment/create.ts
  packages/scripts/src/commands/deployment/get.ts
  packages/scripts/src/commands/deployment/index.ts
  packages/scripts/src/commands/deployment/set.ts
  packages/scripts/src/commands/deployment/templates/config.default.ts
  packages/scripts/src/commands/deployment/templates/config.extended.ts
  packages/scripts/src/commands/deployment/utils.ts
  packages/scripts/src/commands/index.ts
  packages/scripts/src/commands/workflow/run.ts
  packages/scripts/src/paths.ts
  packages/scripts/src/utils/file-utils.ts
  packages/shared/package.json
  packages/test-visual/package.json
  packages/translations/package.json
  src/environments/environment.prod.ts
  src/environments/environment.ts
  yarn.lock
Labels: test - preview

#1769 feat: add seo service
  src/app/app.component.ts
  src/app/shared/services/seo/seo.service.spec.ts
  src/app/shared/services/seo/seo.service.ts
  src/index.html
Labels: test - preview

#1776 refactor: app-data contents json
  package.json
  packages/app-data/assets/contents.json
  packages/app-data/assets/index.ts
  packages/app-data/index.ts
  packages/app-data/package.json
  packages/app-data/sheets/contents.json
  packages/app-data/sheets/index.ts
  packages/app-data/translations/contents.json
  packages/app-data/translations/index.ts
  packages/app-data/tsconfig.json
  packages/data-models/deployment.model.ts
  packages/scripts/src/commands/app-data/copy.ts
  packages/test-visual/package.json
  packages/test-visual/src/commands/generate.ts
  packages/test-visual/src/config/index.ts
  packages/test-visual/src/config/test.ts
  src/app/data/app-data.ts
  src/app/data/index.ts
  yarn.lock
Labels: test - visual

#1734 chore: add error dsns
  .idems_app/deployments/plh_tz/config.ts
  .idems_app/deployments/plh_za/config.ts
  packages/app-data/sheets/data_list/lifecycle_actions/launch_actions.json
  packages/app-data/sheets/template/accept_terms.json
  packages/app-data/sheets/template/app_menu_terms.json
  src/app/shared/services/crashlytics/crashlytics.service.ts
Labels: test - preview

#1778 Update ParentApp icon
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  packages/app-data/assets/contents.json
  packages/app-data/assets/global/android/icon-background.png
  packages/app-data/assets/global/android/icon-foreground.png
  packages/app-data/assets/global/android/icon.png
Labels: test - appetize

#1786 Update ParentApp content 9 Feb 2023
  packages/app-data/assets/contents.json
  packages/app-data/sheets/contents.json
  packages/app-data/sheets/data_list/check_in_data.json
  packages/app-data/sheets/template/w_1on1_welcome_individual.json
  packages/app-data/sheets/template/w_celebrate_welcome_individual.json
  packages/app-data/sheets/template/w_consequence_welcome_ind.json
  packages/app-data/sheets/template/w_crisis_welcome_individual.json
  packages/app-data/sheets/template/w_instruct_welcome_individual.json
  packages/app-data/sheets/template/w_money_welcome_individual.json
  packages/app-data/sheets/template/w_praise_welcome_individual.json
  packages/app-data/sheets/template/w_rules_welcome_individual.json
  packages/app-data/sheets/template/w_safe_welcome_individual.json
  packages/app-data/sheets/template/w_self_care_welcome_individual.json
  packages/app-data/sheets/template/w_solve_welcome_individual.json
  packages/app-data/sheets/template/w_stress_welcome_individual.json
  packages/app-data/sheets/template/welcome_individual.json
Labels: test - preview

#1783 fix: feedback template path
  documentation/docs/authors/feedback.md
  documentation/docs/authors/images/feedback-sidebar.png
  packages/app-data/sheets/template/feature_feedback_default.json
  packages/app-data/sheets/template/feature_feedback_text_select.json
  packages/data-models/workflows/sync.workflows.ts
  src/app/feature/feedback/feedback.actions.ts
  src/app/feature/feedback/feedback.module.ts
  src/app/feature/feedback/feedback.service.ts
  src/app/feature/feedback/pages/feedback-debug.page.ts
  src/app/shared/components/template/services/instance/template-action.registry.ts
  src/app/shared/components/template/services/instance/template-action.service.ts
Labels: test - preview

#1784 Feat/hidden sourcemaps
  .github/workflows/deployment-hosting.yml
  .github/workflows/sourcemaps-upload.yml
  .github/workflows/test-preview.yml
  angular.json
Labels: test - preview

#1794 WASH App Content Sync 17/02/2023
  packages/app-data/sheets/data_list/bathing.json
  packages/app-data/sheets/data_list/breastfeeding.json
  packages/app-data/sheets/data_list/clean_latrines.json
  packages/app-data/sheets/data_list/clean_toilets.json
  packages/app-data/sheets/data_list/generated/bathing_tasks.json
  packages/app-data/sheets/data_list/generated/breastfeeding_tasks.json
  packages/app-data/sheets/data_list/generated/clean_latrines_tasks.json
  packages/app-data/sheets/data_list/generated/clean_toilets_tasks.json
  packages/app-data/sheets/data_list/generated/handwashing_tasks.json
  packages/app-data/sheets/data_list/generated/handwashing_with_soap_tasks.json
  packages/app-data/sheets/data_list/generated/healthy_families_tasks.json
  packages/app-data/sheets/data_list/generated/healthy_homes_tasks.json
  packages/app-data/sheets/data_list/generated/how_to_wash_your_hands_tasks.json
  packages/app-data/sheets/data_list/generated/menstrual_hygiene_tasks.json
  packages/app-data/sheets/data_list/generated/module_tasks.json
  packages/app-data/sheets/data_list/generated/safe_drinking_water_tasks.json
  packages/app-data/sheets/data_list/generated/safe_food_tasks.json
  packages/app-data/sheets/data_list/generated/waste_tasks.json
  packages/app-data/sheets/data_list/generated/water_containers_tasks.json
  packages/app-data/sheets/data_list/generated/water_source_tasks.json
  packages/app-data/sheets/data_list/generated/water_treatment_tasks.json
  packages/app-data/sheets/data_list/generated/when_to_wash_your_hands_tasks.json
  packages/app-data/sheets/data_list/handwashing.json
  packages/app-data/sheets/data_list/handwashing_with_soap.json
  packages/app-data/sheets/data_list/healthy_families.json
  packages/app-data/sheets/data_list/healthy_homes.json
  packages/app-data/sheets/data_list/how_to_wash_your_hands.json
  packages/app-data/sheets/data_list/menstrual_hygiene.json
  packages/app-data/sheets/data_list/module.json
  packages/app-data/sheets/data_list/safe_drinking_water.json
  packages/app-data/sheets/data_list/safe_food.json
  packages/app-data/sheets/data_list/waste.json
  packages/app-data/sheets/data_list/water_containers.json
  packages/app-data/sheets/data_list/water_source.json
  packages/app-data/sheets/data_list/water_treatment.json
  packages/app-data/sheets/data_list/when_to_wash_your_hands.json
  packages/app-data/sheets/data_pipe/module_task_completion.json
  packages/app-data/sheets/index.ts
  packages/app-data/sheets/template/module_card.json
  packages/app-data/sheets/template/module_overview.json
  packages/app-data/sheets/template/module_tool.json
  packages/app-data/sheets/template/reference_popup.json
Labels: test - preview

#1797 WASH App content sync 20/02/2023
  packages/app-data/sheets/data_list/bathing.json
  packages/app-data/sheets/data_list/clean_toilets.json
  packages/app-data/sheets/data_list/generated/bathing_tasks.json
  packages/app-data/sheets/data_list/generated/clean_toilets_tasks.json
  packages/app-data/sheets/data_list/generated/handwashing_with_soap_tasks.json
  packages/app-data/sheets/data_list/generated/healthy_families_tasks.json
  packages/app-data/sheets/data_list/generated/healthy_homes_tasks.json
  packages/app-data/sheets/data_list/generated/how_to_wash_your_hands_tasks.json
  packages/app-data/sheets/data_list/generated/module_tasks.json
  packages/app-data/sheets/data_list/generated/safe_drinking_water_tasks.json
  packages/app-data/sheets/data_list/generated/safe_food_tasks.json
  packages/app-data/sheets/data_list/generated/waste_tasks.json
  packages/app-data/sheets/data_list/generated/when_to_wash_your_hands_tasks.json
  packages/app-data/sheets/data_list/handwashing_with_soap.json
  packages/app-data/sheets/data_list/healthy_families.json
  packages/app-data/sheets/data_list/healthy_homes.json
  packages/app-data/sheets/data_list/how_to_wash_your_hands.json
  packages/app-data/sheets/data_list/module.json
  packages/app-data/sheets/data_list/safe_drinking_water.json
  packages/app-data/sheets/data_list/safe_food.json
  packages/app-data/sheets/data_list/waste.json
  packages/app-data/sheets/data_list/when_to_wash_your_hands.json
Labels: test - preview
