Repository IDEMSInternational/open-app-builder, pull requests merged in 2023-03, with the labels that each got.

#1802 feat: reschedule campaign notifications when the highlighted task group changes
  src/app/feature/campaign/campaign.service.ts
  src/app/shared/components/template/components/task-progress-bar/task-progress-bar.component.ts
  src/app/shared/components/template/services/instance/template-action.service.ts
  src/app/shared/services/task/task.service.ts
Labels: test - preview

#1809 Update PLH config
  .idems_app/deployments/plh/config.ts
  .idems_app/deployments/plh/skins/index.ts
  .idems_app/deployments/plh/skins/weekly_workshop.ts
Labels: test - preview

#1823 WASH Preview update ahead of release v0.16.2
  .idems_app/deployments/plh/config.ts
  .idems_app/deployments/plh/skins/index.ts
  .idems_app/deployments/plh/skins/weekly_workshop.ts
  android/app/build.gradle
  android/app/src/main/java/international/idems/wash/MainActivity.java
  package.json
  packages/app-data/assets/contents.json
  packages/app-data/sheets/contents.json
  packages/app-data/sheets/template/legal_terms/app_menu_privacy_policy.json
  packages/app-data/sheets/template/legal_terms/app_menu_terms.json
Labels: test - preview

#1820 Update ParentApp content 3 March 2023
  packages/app-data/assets/contents.json
  packages/app-data/assets/global/plh_images/first_app_launch/frustrated.svg
  packages/app-data/assets/global/plh_images/first_app_launch/frustrated_shadow.svg
  packages/app-data/assets/global/plh_images/first_app_launch/loving_parent.svg
  packages/app-data/assets/global/plh_images/first_app_launch/loving_parent_shadow.svg
  packages/app-data/assets/global/plh_images/first_app_launch/parent_group.svg
  packages/app-data/assets/global/plh_images/first_app_launch/parent_phone.svg
  packages/app-data/assets/global/plh_images/workshops/w_self_care/guide_1/recognise.svg
  packages/app-data/assets/global/plh_images/workshops/w_self_care/guide_1/reward.svg
  packages/app-data/assets/global/plh_images/workshops/w_self_care/individual/recognise.svg
  packages/app-data/assets/global/plh_images/workshops/w_self_care/individual/reward.svg
  packages/app-data/assets/theme_professional/global/plh_images/first_app_launch/frustrated.svg
  packages/app-data/assets/theme_professional/global/plh_images/first_app_launch/loving_parent.svg
  packages/app-data/assets/theme_professional/global/plh_images/first_app_launch/parent_phone.svg
  packages/app-data/assets/theme_professional/global/plh_images/workshops/w_self_care/individual/recognise.svg
  packages/app-data/assets/theme_professional/global/plh_images/workshops/w_self_care/individual/reward.svg
  packages/app-data/sheets/contents.json
  packages/app-data/sheets/data_list/hp_challenges_data.json
  packages/app-data/sheets/data_list/parent_centre_data_list.json
  packages/app-data/sheets/template/complete_app_update.json
  packages/app-data/sheets/template/parent_centre_help.json
  packages/app-data/sheets/template/parent_centre_support_con.json
  packages/app-data/sheets/template/parent_centre_technical_support.json
  packages/app-data/sheets/template/splash_screens.json
  packages/app-data/sheets/template/w_self_care_recognise.json
  packages/app-data/sheets/template/w_self_care_reward.json
  packages/app-data/sheets/tour/home_screen_modular_tour_menu.json
Labels: test - preview, test - appetize

#1842 Update ParentApp icon and splash screen
  android/app/src/main/res/drawable-land-hdpi/splash.png
  android/app/src/main/res/drawable-land-mdpi/splash.png
  android/app/src/main/res/drawable-land-xhdpi/splash.png
  android/app/src/main/res/drawable-land-xxhdpi/splash.png
  android/app/src/main/res/drawable-land-xxxhdpi/splash.png
  android/app/src/main/res/drawable-port-hdpi/splash.png
  android/app/src/main/res/drawable-port-mdpi/splash.png
  android/app/src/main/res/drawable-port-xhdpi/splash.png
  android/app/src/main/res/drawable-port-xxhdpi/splash.png
  android/app/src/main/res/drawable-port-xxxhdpi/splash.png
  android/app/src/main/res/drawable/splash.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_background.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  packages/app-data/assets/global/android/icon-background.png
  packages/app-data/assets/global/android/icon-foreground.png
  packages/app-data/assets/global/android/icon.png
  packages/app-data/assets/global/android/splash.png
Labels: test - appetize

#1793 refactor: feedback actions
  documentation/docs/authors/feedback.md
  packages/data-models/appConfig.ts
  src/app/app.component.ts
  src/app/feature/feedback/components/feedback-toolbar/feedback-toolbar.component.html
  src/app/feature/feedback/components/feedback-toolbar/feedback-toolbar.component.ts
  src/app/feature/feedback/feedback.service.ts
  src/app/feature/feedback/pages/feedback-debug.page.html
Labels: test - preview

#1859 ParentApp TZ update v0.16.15
  android/app/build.gradle
  package.json
  packages/app-data/translations/tz_sw/strings.json
  packages/app-data/translations_source/from_translators/translated.tz_sw.json
Labels: test - preview

#1861 fix: navigation not progressing after completing w_self_care_reward with tz override
  android/app/build.gradle
  package.json
  packages/app-data/sheets/template/w_self_care_reward_tz.json
Labels: test - preview

#1848 feat: add radio_group_grid component
  .idems_app/deployments/local/sheets/demo.xlsx
  packages/data-models/flowTypes.ts
  src/app/shared/components/template/components/index.ts
  src/app/shared/components/template/components/radio-button-grid/radio-button-grid.component.html
  src/app/shared/components/template/components/radio-button-grid/radio-button-grid.component.scss
  src/app/shared/components/template/components/radio-button-grid/radio-button-grid.component.spec.ts
  src/app/shared/components/template/components/radio-button-grid/radio-button-grid.component.ts
  src/app/shared/components/template/components/radio-group/radio-group.component.ts
  src/theme/themes/default.scss
  src/theme/themes/professional.scss
Labels: test - preview

#1864 ci: enable test-appetize for deployment/* branches
  .github/workflows/test-appetize.yml
Labels: test - appetize

#1868 WASH App deployment update 30 Mar 2023
  .github/workflows/test-appetize.yml
  .idems_app/deployments/local/sheets/demo.xlsx
  android/app/build.gradle
  package.json
  packages/app-data/sheets/global/nav_button_globals.json
  packages/app-data/translations/tz_sw/strings.json
  packages/app-data/translations_source/from_translators/translated.tz_sw.json
  packages/data-models/flowTypes.ts
  src/app/shared/components/template/components/index.ts
  src/app/shared/components/template/components/radio-button-grid/radio-button-grid.component.html
  src/app/shared/components/template/components/radio-button-grid/radio-button-grid.component.scss
  src/app/shared/components/template/components/radio-button-grid/radio-button-grid.component.spec.ts
  src/app/shared/components/template/components/radio-button-grid/radio-button-grid.component.ts
  src/app/shared/components/template/components/radio-group/radio-group.component.ts
  src/theme/themes/default.scss
  src/theme/themes/professional.scss
Labels: test - preview, test - appetize
