Repository IDEMSInternational/open-app-builder, pull requests merged in 2023-01, with the labels that each got.

#1697 chore: update rxjs 6 to 7
  package.json
  src/app/feature/feedback/pages/feedback-debug.page.ts
  src/app/shared/components/debug-toggle.ts
  src/app/shared/components/template/components/combo-box/combo-box.component.ts
  src/app/shared/components/template/components/radio-group/radio-group.component.ts
  src/app/shared/components/template/components/select-text/select-text.component.ts
  src/app/shared/components/template/services/instance/template-action.service.ts
  src/app/shared/components/template/template-container.component.ts
  src/app/shared/services/asyncService.base.ts
  src/app/shared/services/auth/auth.service.ts
  src/app/shared/services/data/app-data.service.ts
  src/app/shared/services/db/db-sync.service.ts
  yarn.lock
Labels: test - preview

#1715 fix: removed margins around hidden nested elements
  src/app/shared/components/template/components/layout/display_group.scss
  src/app/shared/components/template/template-component.scss
Labels: test - visual, test - preview

#1718 style: swap colours of parent points' clicked/unclicked state, and add border, in professional theme
  src/app/shared/components/template/components/points-item/points-item.component.scss
  src/app/shared/components/template/components/task-card/task-card.component.scss
  src/theme/themes/default.scss
  src/theme/themes/professional.scss
Labels: test - visual, test - preview

#1738 Deployment dev/wash
  packages/app-data/assets/global/essential_tools/Archive/HandwashingDisgust.png
  packages/app-data/assets/global/essential_tools/Archive/cleaning_container.png
  packages/app-data/assets/global/essential_tools/Archive/hands_with_soap.jpg
  packages/app-data/assets/global/essential_tools/Archive/handwashing_how.png
  packages/app-data/assets/global/essential_tools/Archive/handwashing_how_1.png
  packages/app-data/assets/global/essential_tools/Archive/healthy homes_clean compound.png
  packages/app-data/assets/global/essential_tools/Archive/home_handwashing.png
  packages/app-data/assets/global/essential_tools/Archive/home_healthy_homes.png
  packages/app-data/assets/global/essential_tools/Archive/home_latrines.png
  packages/app-data/assets/global/essential_tools/Archive/home_safe_food.png
  packages/app-data/assets/global/essential_tools/Archive/home_shower.png
  packages/app-data/assets/global/essential_tools/Archive/home_waste_license_needed.png
  packages/app-data/assets/global/essential_tools/Archive/home_water_containers.png
  packages/app-data/assets/global/essential_tools/Archive/home_water_source.png
  packages/app-data/assets/global/essential_tools/Archive/home_water_treatment_license_needed.png
  packages/app-data/assets/global/essential_tools/Archive/housing.svg
  packages/app-data/assets/global/essential_tools/Archive/jerrycan_license_needed.png
  packages/app-data/assets/global/essential_tools/Archive/soap.png
  packages/app-data/assets/global/essential_tools/Archive/water_germs_license_needed.png
  packages/app-data/assets/global/essential_tools/handwash_need.svg
  packages/app-data/assets/global/essential_tools/home_family.png
  packages/app-data/assets/global/essential_tools/home_family.svg
  packages/app-data/assets/global/essential_tools/home_healthy_homes.svg
  packages/app-data/assets/global/essential_tools/home_latrine.svg
  packages/app-data/assets/global/essential_tools/home_safe_food.svg
  packages/app-data/assets/index.ts
  packages/app-data/sheets/data_list/bathing.json
  packages/app-data/sheets/data_list/breastfeeding.json
  packages/app-data/sheets/data_list/clean_latrines.json
  packages/app-data/sheets/data_list/generated/bathing_tasks.json
  packages/app-data/sheets/data_list/generated/breastfeeding_tasks.json
  packages/app-data/sheets/data_list/generated/clean_latrines_tasks.json
  packages/app-data/sheets/data_list/generated/handwashing_tasks.json
  packages/app-data/sheets/data_list/generated/healthy_families_tasks.json
  packages/app-data/sheets/data_list/generated/healthy_homes_tasks.json
  packages/app-data/sheets/data_list/generated/menstrual_hygiene_tasks.json
  packages/app-data/sheets/data_list/generated/module_tasks.json
  packages/app-data/sheets/data_list/generated/safe_food_tasks.json
  packages/app-data/sheets/data_list/generated/waste_tasks.json
  packages/app-data/sheets/data_list/generated/water_containers_tasks.json
  packages/app-data/sheets/data_list/generated/water_source_tasks.json
  packages/app-data/sheets/data_list/generated/water_treatment_tasks.json
  packages/app-data/sheets/data_list/handwashing.json
  packages/app-data/sheets/data_list/healthy_families.json
  packages/app-data/sheets/data_list/healthy_homes.json
  packages/app-data/sheets/data_list/menstrual_hygiene.json
  packages/app-data/sheets/data_list/module.json
  packages/app-data/sheets/data_list/safe_food.json
  packages/app-data/sheets/data_list/waste.json
  packages/app-data/sheets/data_list/water_containers.json
  packages/app-data/sheets/data_list/water_source.json
  packages/app-data/sheets/data_list/water_treatment.json
  packages/app-data/sheets/data_pipe/module_task_completion.json
  packages/app-data/sheets/index.ts
Labels: test - preview

#1603 Feat/feedback sidebar
  package.json
  packages/data-models/flowTypes.ts
  src/app/app.component.ts
  src/app/feature/feedback/components/feedback-toolbar/feedback-toolbar.component.html
  src/app/feature/feedback/components/feedback-toolbar/feedback-toolbar.component.scss
  src/app/feature/feedback/components/feedback-toolbar/feedback-toolbar.component.spec.ts
  src/app/feature/feedback/components/feedback-toolbar/feedback-toolbar.component.ts
  src/app/feature/feedback/components/index.ts
  src/app/feature/feedback/feedback.actions.ts
  src/app/feature/feedback/feedback.module.ts
  src/app/feature/feedback/feedback.service.ts
  src/app/feature/feedback/feedback.types.ts
  src/app/feature/feedback/pages/feedback-debug.page.html
  src/app/feature/feedback/pages/feedback-debug.page.ts
  src/app/feature/feedback/routeGuards.ts
  src/app/shared/components/template/services/instance/template-action.registry.ts
  src/app/shared/components/template/services/instance/template-action.service.ts
  src/app/shared/components/template/services/template-field.service.ts
  yarn.lock
Labels: test - preview, test - appetize

#1748 Fix: styling of task-card with button style can handle longer strings of text
  src/app/shared/components/template/components/task-card/task-card.component.scss
Labels: test - visual

#1756 feat: add support for deployment workflows
  .github/workflows/android-build.yml
  .github/workflows/android-release.yml
  .github/workflows/deployment-hosting.yml
  .github/workflows/deprecated/build-and-upload.yml
  .github/workflows/deprecated/pr-build.yml
  .github/workflows/sourcemaps-upload.yml
  .github/workflows/test-appetize.yml
  .github/workflows/test-build.yml
  .github/workflows/test-preview.yml
  .github/workflows/test-visual-compare.yml
  .github/workflows/test-visual-generate.yml
  README.md
  documentation/docs/authors/local-sheets.md
  documentation/docs/developers/deployments.md
  documentation/docs/generated/index.html
  documentation/docs/generated/js/search/search_index.js
  documentation/docs/index.md
  packages/data-models/deployment.model.ts
  packages/data-models/workflows/deployment.workflows.ts
  packages/data-models/workflows/index.ts
  packages/data-models/workflows/workflow.model.ts
  packages/scripts/src/commands/deployment/get.ts
  packages/scripts/src/commands/deployment/set.ts
  packages/scripts/src/commands/workflow/index.ts
  packages/scripts/src/commands/workflow/run.ts
  packages/scripts/src/tasks/index.ts
  packages/scripts/src/tasks/providers/deployment.ts
Labels: test - preview
