Repository IDEMSInternational/open-app-builder, pull requests merged in 2024-10, with the labels that each got.

#2440 Fix: generator chained flows
  .idems_app/deployments/local/.gitignore
  packages/data-models/flowTypes.ts
  packages/scripts/src/commands/app-data/convert/cacheStrategy/jsonFile.mock.ts
  packages/scripts/src/commands/app-data/convert/cacheStrategy/jsonFile.ts
  packages/scripts/src/commands/app-data/convert/convert.spec.ts
  packages/scripts/src/commands/app-data/convert/processors/base.ts
  packages/scripts/src/commands/app-data/convert/processors/flowParser/flowParser.spec.ts
  packages/scripts/src/commands/app-data/convert/processors/flowParser/flowParser.ts
  packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/data_pipe.parser.spec.ts
  packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/data_pipe.parser.ts
  packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/default.parser.ts
  packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/generator.parser.spec.ts
  packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/generator.parser.ts
  packages/scripts/src/commands/app-data/postProcess/sheets.ts
  packages/shared/src/models/templatedData/templatedData.spec.ts
  packages/shared/src/models/templatedData/templatedData.ts
Labels: scripts, fix

#2446 Ensure CNAME file is copied over to built docs site
  .github/workflows/documentation-deploy.yml
  documentation/docs/CNAME
Labels: documentation

#2452 feat(parser): add output references to for gen flows
  packages/data-models/flowTypes.ts
  packages/scripts/src/commands/app-data/convert/convert.spec.ts
  packages/scripts/src/commands/app-data/convert/processors/flowParser/flowParser.spec.ts
  packages/scripts/src/commands/app-data/convert/processors/flowParser/flowParser.ts
  packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/data_pipe.parser.spec.ts
  packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/data_pipe.parser.ts
  packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/generator.parser.spec.ts
  packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/generator.parser.ts
Labels: scripts

#2450 fix(report): track assets with preceding forward slash
  packages/scripts/src/commands/app-data/report/reporters/asset-summary.spec.ts
  packages/scripts/src/commands/app-data/report/reporters/asset-summary.ts
  packages/shared/src/utils/string-utils.ts
  src/app/shared/components/template/services/template-asset.service.ts
Labels: scripts, fix

#2453 Change custom domain for docs site
  documentation/docs/CNAME
Labels: documentation

#2458 fix(map): handle non-normalised values in heatmap layer property scale
  src/app/shared/components/template/components/map/map.component.ts
Labels: fix

#2448 feat: audio component 'compact' variant; refactor audio component logic
  src/app/shared/components/template/components/audio/audio.component.html
  src/app/shared/components/template/components/audio/audio.component.scss
  src/app/shared/components/template/components/audio/audio.component.ts
  src/app/shared/components/template/pipes/plh-asset.pipe.ts
  src/theme/deployment/_overrides.scss
Labels: feature, test - preview

#2462 fix: encrypted deployment set
  packages/scripts/src/commands/deployment/set.ts
  packages/scripts/src/commands/deployment/utils.ts
  packages/workflows/src/deployment.workflows.ts
Labels: scripts, test - preview, fix

#2464 chore: refactor text component
  src/app/shared/components/template/components/index.ts
  src/app/shared/components/template/components/text.ts
  src/app/shared/components/template/components/text/text.component.html
  src/app/shared/components/template/components/text/text.component.ts
Labels: maintenance

#2460 feat: audio component can be passed transcript text and launch own popup
  src/app/shared/components/template/components/audio/audio.component.html
  src/app/shared/components/template/components/audio/audio.component.scss
  src/app/shared/components/template/components/audio/audio.component.ts
  src/app/shared/components/template/components/layout/popup/popup.component.html
  src/app/shared/components/template/components/layout/popup/popup.component.ts
Labels: feature, test - preview

#2468 feat: add plh_kids_kw theme
  src/theme/themes/_index.scss
  src/theme/themes/plh_kids_kw.scss
  src/theme/variables.scss
Labels: feature

#2461 refactor: app-data-evaluator
  packages/shared/README.md
  packages/shared/src/models/appDataEvaluator/appDataEvaluator.spec.ts
  packages/shared/src/models/appDataEvaluator/appDataEvaluator.ts
  packages/shared/src/models/appStringEvaluator/appStringEvaluator.spec.ts
  packages/shared/src/models/appStringEvaluator/appStringEvaluator.ts
  packages/shared/src/models/dataPipe/operators/appendColumns.ts
  packages/shared/src/models/index.ts
  packages/shared/src/utils/delimiters.spec.ts
  packages/shared/src/utils/delimiters.ts
  src/app/shared/services/data/app-data-variable.service.ts
Labels: maintenance

#2471 [FEATURE] Nunito Default Font
  src/assets/fonts/nunito-v26-latin/nunito-v26-latin-300.woff2
  src/assets/fonts/nunito-v26-latin/nunito-v26-latin-500.woff2
  src/assets/fonts/nunito-v26-latin/nunito-v26-latin-500italic.woff2
  src/assets/fonts/nunito-v26-latin/nunito-v26-latin-600.woff2
  src/assets/fonts/nunito-v26-latin/nunito-v26-latin-600italic.woff2
  src/assets/fonts/nunito-v26-latin/nunito-v26-latin-700.woff2
  src/assets/fonts/nunito-v26-latin/nunito-v26-latin-700italic.woff2
  src/assets/fonts/nunito-v26-latin/nunito-v26-latin-800.woff2
  src/assets/fonts/nunito-v26-latin/nunito-v26-latin-800italic.woff2
  src/assets/fonts/nunito-v26-latin/nunito-v26-latin-900.woff2
  src/assets/fonts/nunito-v26-latin/nunito-v26-latin-900italic.woff2
  src/assets/fonts/nunito-v26-latin/nunito-v26-latin-italic.woff2
  src/assets/fonts/nunito-v26-latin/nunito-v26-latin-regular.woff2
  src/theme/themes/plh_kids_kw.scss
Labels: feature

#2482 chore: update husky hook
  .husky/pre-commit
Labels: maintenance

#2481 refactor: plh_kw theme folder
  src/app/shared/components/template/components/accordion/accordion.component.scss
  src/app/shared/components/template/components/audio/audio.component.scss
  src/app/shared/components/template/components/button/button.component.scss
  src/theme/themes/_index.scss
  src/theme/themes/plh_kids_kw/_index.scss
  src/theme/themes/plh_kids_kw/_overrides.scss
  src/theme/themes/plh_kids_kw/_typography.scss
Labels: maintenance

#2478 chore: add plh component folder and example component
  packages/components/demo/README.md
  packages/components/demo/basic/basic.component.html
  packages/components/demo/basic/basic.component.scss
  packages/components/demo/basic/basic.component.spec.ts
  packages/components/demo/basic/basic.component.ts
  packages/components/demo/index.ts
  packages/components/plh/index.ts
  src/app/shared/components/template/components/index.ts
  src/theme/themes/default.scss
Labels: maintenance

#2483 fix: app-data evaluator
  packages/scripts/src/commands/app-data/convert/processors/flowParser/flowParser.ts
  packages/shared/src/models/appDataEvaluator/appDataEvaluator.spec.ts
  packages/shared/src/models/appDataEvaluator/appDataEvaluator.ts
  packages/shared/src/utils/delimiters.spec.ts
  packages/shared/src/utils/delimiters.ts
Labels: scripts, fix

#2485 chore: move plh-specific components to plh components folder
  packages/components/plh/index.ts
  packages/components/plh/parent-point-box/parent-point-box.component.html
  packages/components/plh/parent-point-box/parent-point-box.component.scss
  packages/components/plh/parent-point-box/parent-point-box.component.spec.ts
  packages/components/plh/parent-point-box/parent-point-box.component.ts
  packages/components/plh/parent-point-counter/parent-point-counter.component.html
  packages/components/plh/parent-point-counter/parent-point-counter.component.scss
  packages/components/plh/parent-point-counter/parent-point-counter.component.ts
  packages/data-models/flowTypes.ts
  src/app/shared/components/template/components/index.ts
  src/app/shared/components/template/pipes/index.ts
  src/app/shared/components/template/template.module.ts
Labels: maintenance

#2467 feat!: add support for pinch-zoom
  capacitor.config.template.ts
  packages/data-models/deployment.model.ts
  packages/scripts/src/tasks/providers/android.ts
  packages/scripts/src/tasks/providers/ios.ts
  packages/workflows/src/android.workflows.ts
  packages/workflows/src/ios.workflows.ts
  src/index.html
Labels: feature, scripts, test - preview, breaking

#2408 Feat (remote assets): handle asset pack containing asset overrides
  packages/data-models/assets.model.ts
  packages/data-models/deployment.model.ts
  packages/data-models/flowTypes.ts
  packages/data-models/index.ts
  packages/scripts/src/commands/app-data/postProcess/assets.spec.ts
  packages/scripts/src/commands/app-data/postProcess/assets.ts
  src/app/shared/components/template/components/layout/popup/popup.component.scss
  src/app/shared/services/remote-asset/remote-asset.service.spec.ts
  src/app/shared/services/remote-asset/remote-asset.service.ts
Labels: scripts, test - preview

#2488 chore: move plh-specific components to plh components folder ALT
  packages/components/plh/index.ts
  packages/components/plh/parent-point-box/parent-point-box.component.html
  packages/components/plh/parent-point-box/parent-point-box.component.scss
  packages/components/plh/parent-point-box/parent-point-box.component.spec.ts
  packages/components/plh/parent-point-box/parent-point-box.component.ts
  packages/components/plh/parent-point-counter/parent-point-counter.component.html
  packages/components/plh/parent-point-counter/parent-point-counter.component.scss
  packages/components/plh/parent-point-counter/parent-point-counter.component.ts
  packages/data-models/flowTypes.ts
  src/app/shared/components/template/components/audio/audio.component.ts
  src/app/shared/components/template/components/index.ts
  src/app/shared/components/template/components/timer/timer.component.ts
  src/app/shared/components/template/pipes/index.ts
  src/app/shared/components/template/pipes/plh-asset.pipe.ts
  src/app/shared/components/template/services/template-asset.service.ts
  src/app/shared/components/template/template.module.ts
Labels: maintenance

#2484 feat: add template base signals and equality check
  packages/components/plh/parent-point-box/parent-point-box.component.ts
  packages/shared/src/utils/object-utils.spec.ts
  packages/shared/src/utils/object-utils.ts
  src/app/shared/components/template/components/base.ts
  src/app/shared/components/template/components/data-items/data-items.component.ts
  src/app/shared/components/template/components/timer/timer.component.ts
Labels: feature

#2491 chore: move arrayToHashmap function
  packages/shared/src/utils/file-utils.ts
  packages/shared/src/utils/object-utils.spec.ts
  packages/shared/src/utils/object-utils.ts
Labels: maintenance

#2492 chore(android): upgrade gradle
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
Labels: test - appetize, maintenance

#2493 review: 2490
  cspell.config.yml
  src/app/shared/components/template/components/youtube/youtube.component.html
  src/app/shared/components/template/components/youtube/youtube.component.ts
Labels: maintenance

#2490 feat: youtube component
  cspell.config.yml
  packages/data-models/flowTypes.ts
  src/app/shared/components/template/components/index.ts
  src/app/shared/components/template/components/youtube/youtube.component.html
  src/app/shared/components/template/components/youtube/youtube.component.scss
  src/app/shared/components/template/components/youtube/youtube.component.spec.ts
  src/app/shared/components/template/components/youtube/youtube.component.ts
  src/app/shared/components/template/services/template-translate.service.ts
Labels: feature, test - preview

#2496 chore: make legend scales horizontal; move legend to under map
  src/app/shared/components/template/components/map/map.component.scss
  src/app/shared/components/template/components/map/map.component.ts
Labels: maintenance

#2495 feat: screen_orientation action
  android/app/capacitor.build.gradle
  android/app/src/main/assets/capacitor.plugins.json
  android/capacitor.settings.gradle
  ios/App/Podfile
  ios/App/Podfile.lock
  package.json
  packages/data-models/flowTypes.ts
  src/app/app.component.ts
  src/app/shared/services/screen-orientation/screen-orientation.service.spec.ts
  src/app/shared/services/screen-orientation/screen-orientation.service.ts
  yarn.lock
Labels: feature
