Repository IDEMSInternational/open-app-builder, pull requests merged in 2024-07, with the labels that each got.

#2350 chore: remove unused test-appetize workflow file
  .github/workflows/test-appetize.yml
Labels: maintenance

#2354 refactor: 2353 text bubble implementation
  packages/data-models/flowTypes.ts
  src/app/shared/components/template/components/index.ts
  src/app/shared/components/template/components/layout/display-group/display-group.component.html
  src/app/shared/components/template/components/layout/display-group/display-group.component.scss
  src/app/shared/components/template/components/layout/display-group/display-group.component.ts
  src/app/shared/components/template/components/text-bubble/text-bubble.component.html
  src/app/shared/components/template/components/text-bubble/text-bubble.component.scss
  src/app/shared/components/template/components/text-bubble/text-bubble.component.ts
Labels: maintenance

#2355 feat: add EFM theme
  src/theme/themes/_index.scss
  src/theme/themes/early_family_math.scss
  src/theme/variables.scss
Labels: feature

#2353 feat: new component, 'text_bubble'
  packages/data-models/flowTypes.ts
  src/app/shared/components/template/components/index.ts
  src/app/shared/components/template/components/layout/display-group/display-group.component.scss
  src/app/shared/components/template/components/layout/display-group/display-group.component.ts
  src/app/shared/components/template/components/text-bubble/text-bubble.component.html
  src/app/shared/components/template/components/text-bubble/text-bubble.component.scss
  src/app/shared/components/template/components/text-bubble/text-bubble.component.ts
Labels: feature

#2348 Fix/popup close button
  packages/scripts/bin/app-scripts
  packages/scripts/bin/app-workflow
  src/app/shared/components/template/components/layout/popup/popup.component.scss
Labels: test - preview
