Repository IDEMSInternational/open-app-builder, pull requests merged in 2024-11, with the labels that each got.

#2497 feat: add slider/filter fucntionality, toggled on for a given layer via the scale_slider property
  src/app/shared/components/template/components/map/map.component.html
  src/app/shared/components/template/components/map/map.component.scss
  src/app/shared/components/template/components/map/map.component.ts
Labels: feature

#2494 Chore: items code tidying
  packages/data-models/appConfig.ts
  packages/data-models/flowTypes.ts
  packages/data-models/functions.ts
  src/app/shared/components/template/components/data-items/data-items.component.ts
  src/app/shared/components/template/processors/item.ts
  src/app/shared/components/template/processors/itemPipe.spec.ts
  src/app/shared/components/template/processors/itemPipe.ts
  src/app/shared/components/template/services/instance/template-row.service.ts
Labels: maintenance

#2505 feat: deployment clone progress
  packages/scripts/src/tasks/providers/git.ts
Labels: scripts, maintenance

#2506 chore: fix linebreaks
  packages/scripts/src/commands/app-data/convert/index.ts
  packages/scripts/src/commands/app-data/convert/utils/app-data-string.utils.ts
Labels: scripts, maintenance

#2498 fix: text bubble component handles markdown
  src/app/shared/components/template/components/text-bubble/text-bubble.component.html
  src/app/shared/components/template/components/text-bubble/text-bubble.component.scss
  src/app/shared/components/template/components/text/text.component.html
  src/app/shared/components/template/components/text/text.component.scss
  src/app/shared/components/template/components/text/text.component.ts
  src/theme/_typography.scss
Labels: test - visual, test - preview, fix

#2504 feat: display group variant box white
  src/app/shared/components/template/components/layout/display-group/display-group.component.scss
  src/app/shared/components/template/components/layout/display-group/display-group.component.ts
Labels: feature, test - preview, styling

#2501 Feat: landscape mode
  packages/data-models/flowTypes.ts
  src/app/app.component.ts
  src/app/feature/template/template.page.html
  src/app/feature/template/template.page.ts
  src/app/shared/components/template/services/template-metadata.service.spec.ts
  src/app/shared/components/template/services/template-metadata.service.ts
  src/app/shared/components/template/services/template.service.ts
  src/app/shared/services/screen-orientation/screen-orientation.service.ts
  src/app/shared/utils/angular.utils.ts
Labels: feature

#2514 feat: full screen template screen orientation tracking
  src/app/shared/components/template/services/template-metadata.service.ts
  src/app/shared/components/template/services/template.service.ts
Labels: feature

#2518 chore: update local demo sheet
  .idems_app/deployments/local/sheets/demo.xlsx
Labels: maintenance

#2517 fix: seo service config
  src/app/shared/services/seo/seo.service.ts
Labels: fix

#2525 fix: fix map rendering on navigation
  src/app/shared/components/template/components/map/map.component.html
  src/app/shared/components/template/components/map/map.component.ts
Labels: fix

#2427 Refactor: app config and header component signals
  src/app/app.component.html
  src/app/app.component.ts
  src/app/shared/components/header/header.component.html
  src/app/shared/components/header/header.component.ts
Labels: scripts, maintenance

#2513 Feat: set data action standalone
  packages/data-models/flowTypes.ts
  packages/shared/src/utils/object-utils.ts
  src/app/shared/components/template/services/instance/template-action.registry.ts
  src/app/shared/components/template/services/template-field.service.spec.ts
  src/app/shared/services/data/app-data.service.spec.ts
  src/app/shared/services/dynamic-data/adapters/persistedMemory.ts
  src/app/shared/services/dynamic-data/dynamic-data.actions.spec.ts
  src/app/shared/services/dynamic-data/dynamic-data.actions.ts
  src/app/shared/services/dynamic-data/dynamic-data.service.mock.spec.ts
  src/app/shared/services/dynamic-data/dynamic-data.service.spec.ts
  src/app/shared/services/dynamic-data/dynamic-data.service.ts
  src/app/shared/services/dynamic-data/dynamic-data.utils.spec.ts
  src/app/shared/services/dynamic-data/dynamic-data.utils.ts
  src/app/shared/services/error-handler/error-handler.service.mock.spec.ts
  src/app/shared/services/error-handler/error-handler.service.spec.ts
Labels: feature, test - preview

#2527 Kuwait Theme: Module List Item Component
  packages/components/plh/index.ts
  packages/components/plh/plh-kids-kw/components/module-list-item/module-list-item.component.html
  packages/components/plh/plh-kids-kw/components/module-list-item/module-list-item.component.scss
  packages/components/plh/plh-kids-kw/components/module-list-item/module-list-item.component.spec.ts
  packages/components/plh/plh-kids-kw/components/module-list-item/module-list-item.component.ts
  src/theme/themes/plh_kids_kw/_overrides.scss
Labels: feature, test - preview

#2529 Feat: data list metadata
  packages/data-models/flowTypes.ts
  packages/scripts/src/commands/app-data/convert/processors/flowParser/flowParser.ts
  packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/data_list.parser.spec.ts
  packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/data_list.parser.ts
  packages/scripts/test/helpers/utils.ts
Labels: feature, scripts

#2520 Feat: deployment build optimisation
  .gitignore
  angular.json
  package.json
  packages/components/package.json
  packages/components/plh/index.ts
  packages/components/plh/manifest.ts
  packages/components/types.ts
  packages/data-models/deployment.model.ts
  packages/data-models/flowTypes.ts
  packages/scripts/src/commands/app-data/optimise/index.ts
  packages/scripts/src/commands/app-data/optimise/optimise.types.ts
  packages/scripts/src/commands/app-data/optimise/optimisers/components.spec.ts
  packages/scripts/src/commands/app-data/optimise/optimisers/components.ts
  packages/scripts/src/commands/app-data/report/report.ts
  packages/scripts/src/commands/app-data/report/report.types.ts
  packages/scripts/src/commands/app-data/report/reporters/template-summary.ts
  packages/scripts/src/tasks/providers/appData.ts
  packages/workflows/src/misc.workflows.ts
  packages/workflows/src/sync.workflows.ts
  src/app/shared/components/template/components/base.ts
  src/app/shared/components/template/components/index.ts
  src/app/shared/components/template/components/layout/form.ts
  src/app/shared/components/template/components/manifest.ts
  yarn.lock
Labels: feature, scripts

#2548 feat(map): legend displayed over map; exposes option to display map layer controls in dropdown
  src/app/shared/components/template/components/map/map.component.html
  src/app/shared/components/template/components/map/map.component.scss
  src/app/shared/components/template/components/map/map.component.ts
Labels: feature

#2563 fix: get boolean param from template row
  src/app/shared/utils/utils.ts
Labels: test - visual, fix

#2530 Refactor: latex and qrcode pipes
  package.json
  src/app/shared/components/template/components/latex/latex.component.ts
  src/app/shared/components/template/components/latex/latex.utils.ts
  src/app/shared/components/template/components/qr-code/qr-code.component.html
  src/app/shared/components/template/components/qr-code/qr-code.component.ts
  src/app/shared/components/template/pipes/index.ts
  src/app/shared/components/template/pipes/latex.pipe.ts
  src/app/shared/components/template/pipes/qr-code.pipe.ts
  yarn.lock
Labels: scripts, maintenance

#2521 Kuwait Theme: Component styling Updates
  .husky/pre-push
  src/app/shared/components/template/components/text-bubble/text-bubble.component.html
  src/app/shared/components/template/components/text-bubble/text-bubble.component.scss
  src/app/shared/components/template/components/text-bubble/text-bubble.component.ts
  src/theme/themes/plh_kids_kw/_index.scss
  src/theme/themes/plh_kids_kw/_overrides.scss
Labels: test - preview, styling

#2556 chore: remove gdrive sync credentials
  documentation/docs/authors/quickstart.md
  packages/@idemsInternational/gdrive-tools/credentials.dev.json
  packages/@idemsInternational/gdrive-tools/src/paths.ts
  packages/scripts/.gitignore
  packages/scripts/config/.gitkeep
  packages/scripts/config/credentials.json.enc
  packages/scripts/config/public.key
  packages/scripts/src/commands/config/decrypt.ts
  packages/scripts/src/commands/config/encrypt.ts
  packages/scripts/src/commands/config/index.ts
  packages/scripts/src/commands/index.ts
Labels: documentation, scripts, maintenance

#2566 fix: plh-module-list-item styling
  src/theme/themes/plh_kids_kw/_overrides.scss
Labels: fix
