Repository IDEMSInternational/open-app-builder, pull requests merged in 2024-08, with the labels that each got.

#2369 feat: add basic legend to map component
  src/app/shared/components/template/components/map/map.component.html
  src/app/shared/components/template/components/map/map.component.scss
  src/app/shared/components/template/components/map/map.component.ts
Labels: feature

#2372 docs: updates to README and Deployments section
  README.md
  documentation/docs/developers/deployments.md
  documentation/docs/index.md
Labels: documentation

#2373 review: task-journey-component
  cspell.config.yml
  src/app/shared/components/template/components/progress-path/progress-path.component.html
  src/app/shared/components/template/components/progress-path/progress-path.component.scss
  src/app/shared/components/template/components/progress-path/progress-path.component.ts
  src/app/shared/components/template/components/task-card/task-card.component.scss
  src/theme/themes/default.scss
  src/theme/themes/early_family_math.scss
  src/theme/themes/pfr.scss
  src/theme/themes/plh_facilitator_mx.scss
  src/theme/themes/professional.scss
Labels: maintenance

#2374 chore(deps): upgrade Capacitor to version 6
  .gitignore
  android/app/build.template.gradle
  android/app/src/main/res/xml/config.xml
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/variables.gradle
  ios/.gitignore
  ios/App/Podfile.lock
  package.json
  yarn.lock
Labels: maintenance

#2381 fix: circle task card variant fires click action trigger
  src/app/shared/components/template/components/task-card/task-card.component.html
Labels: fix

#2384 fix: progress-path component handles RTL languages
  src/app/shared/components/template/components/progress-path/progress-path.component.html
  src/app/shared/components/template/components/progress-path/progress-path.component.scss
  src/app/shared/components/template/components/progress-path/progress-path.component.ts
Labels: fix

#2382 fix: progress bar should not be visible on task-card button variant
  src/app/shared/components/template/components/task-card/task-card.component.scss
Labels: fix
