Repository IDEMSInternational/open-app-builder, pull requests merged in 2024-04, with the labels that each got.

#2235 feat: deployment-based firebase config
  .firebaserc
  .github/workflows/reusable-app-build.yml
  .github/workflows/reusable-content-sync.yml
  .github/workflows/test-app-build.yml
  .github/workflows/web-build.yml
  .gitignore
  .template.firebaserc
  README.md
  documentation/docs/developers/web-previews.md
  documentation/docs/index.md
  firebase.json
  firebase.template.json
  package.json
  packages/data-models/deployment.model.ts
  packages/scripts/src/commands/deployment/common.ts
  packages/scripts/src/commands/deployment/utils.ts
  packages/scripts/src/commands/index.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/shared/services/auth/auth.service.ts
  src/app/shared/services/crashlytics/crashlytics.service.ts
  src/app/shared/services/error-handler/error-handler.service.ts
  src/app/shared/services/firebase/firebase.service.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/environments/firebaseConfig.sample.ts
  yarn.lock
Labels: documentation, feature

#2255 docs: Android config workflows
  cspell.config.yml
  documentation/docs/developers/android-assets.md
  documentation/docs/developers/deployments.md
  documentation/docs/developers/in-app-updates.md
  documentation/docs/developers/quickstart.md
Labels: documentation

#2256 Feat: templated iOS config
  .gitignore
  ios/App/App.xcodeproj/project.template.pbxproj
  packages/data-models/deployment.model.ts
  packages/scripts/src/tasks/index.ts
  packages/scripts/src/tasks/providers/android.ts
  packages/scripts/src/tasks/providers/ios.ts
  packages/scripts/src/utils.ts
  packages/workflows/src/index.ts
  packages/workflows/src/ios.workflows.ts
Labels: feature

#2269 chore: update default app data output path to reflect remote repos
  packages/data-models/deployment.model.ts
Labels: maintenance

#2270 Feat: user import action
  documentation/docs/developers/server-development.md
  packages/api/.env.example
  packages/api/Dockerfile
  packages/api/package.json
  packages/api/spec-export.json
  packages/api/src/endpoints/app_users/app_user.controller.ts
  packages/api/src/environment/index.ts
  packages/api/src/main.ts
  packages/data-models/flowTypes.ts
  packages/server/README.md
  packages/server/docker/docker-compose.yml
  src/app/shared/components/template/components/select-text/select-text.component.ts
  src/app/shared/components/template/components/text-box/text-box.component.ts
  src/app/shared/components/template/services/template-field.service.ts
  src/app/shared/services/server/interceptors.ts
  src/app/shared/services/userMeta/userMeta.service.ts
Labels: documentation

#2276 fix: android workflow variables
  packages/scripts/src/tasks/providers/android.ts
Labels: fix

#2280 feat: Update plh_facilitator_mx theme
  src/theme/themes/plh_facilitator_mx.scss
Labels: feature

#2278 fix: test actions
  .github/workflows/deprecated/deployment-hosting.yml
  .github/workflows/test-app-build.yml
  .github/workflows/test-build.yml
  .github/workflows/test-preview.yml
  .github/workflows/test-visual.yml
  .github/workflows/web-build.yml
Labels: test - visual, test - preview, fix

#2281 fix: iOS footer bug
  src/app/shared/components/template/components/navigation-bar/navigation-bar.component.scss
Labels: fix

#2289 fix: button child layout positioning
  src/app/shared/components/template/components/button/button.component.html
  src/app/shared/components/template/components/button/button.component.scss
Labels: fix

#2293 Docs: ios; code releases
  cspell.config.yml
  documentation/docs/developers/building-and-deploying-to-ios.md
  documentation/docs/developers/code-releases.md
  documentation/docs/developers/deployments.md
  documentation/docs/developers/images/xcode-target.png
  documentation/mkdocs.yml
Labels: documentation

#2211 Refactor: template parser answer list support
  packages/scripts/src/commands/app-data/convert/processors/base.ts
  packages/scripts/src/commands/app-data/convert/processors/flowParser/flowParser.ts
  packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/default.parser.ts
  packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/template.parser.spec.ts
  packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/template.parser.ts
  packages/scripts/src/commands/app-data/convert/processors/xlsxWorkbook.ts
  packages/scripts/src/commands/app-data/convert/utils/app-data-string.utils.ts
  src/app/shared/components/template/components/navigation-bar/navigation-bar.component.ts
  src/app/shared/components/template/utils/template-utils.ts
  src/app/shared/utils/utils.ts
Labels: test - visual, test - preview

#2299 chore: upgrade prettier package version
  .prettierignore
  .prettierrc
  package.json
  packages/api/package.json
  src/theme/themes/default.scss
  src/theme/themes/pfr.scss
  yarn.lock
Labels: maintenance

#2215 feat: set_item action: optionally target an index or id
  packages/data-models/flowTypes.ts
  src/app/shared/components/template/components/data-items/data-items.component.ts
  src/app/shared/components/template/services/template-calc.service.spec.ts
  src/app/shared/components/template/services/template-field.service.spec.ts
  src/app/shared/components/template/services/template-translate.service.spec.ts
  src/app/shared/components/template/services/template-variables.service.spec.ts
  src/app/shared/components/template/services/template-variables.service.ts
  src/app/shared/services/dynamic-data/dynamic-data.service.spec.ts
  src/app/shared/services/dynamic-data/dynamic-data.service.ts
  src/app/shared/services/error-handler/error-handler.service.spec.ts
Labels: feature, test - preview
