Repository IDEMSInternational/open-app-builder, pull requests merged in 2024-02, with the labels that each got.

#2194 fix: gdrive authorize script
  packages/workflows/src/sync.workflows.ts
Labels: fix

#2192 feat: expose favicon asset path to deployment config
  packages/data-models/deployment.model.ts
  src/app/shared/services/seo/seo.service.ts
Labels: feature

#2203 feat: replace default favicon with IDEMS trefoil
  src/app/shared/services/seo/seo.service.ts
  src/assets/icon/favicon.png
  src/assets/icon/favicon.svg
  src/index.html
Labels: feature

#2206 refactor: use version script in reusable actions
  .github/workflows/reusable-android-build.yml
  documentation/docs/developers/in-app-updates.md
  package.json
  packages/scripts/src/commands/version.ts
Labels: documentation, maintenance

#2204 fix: handle undefined values in answer lists
  src/app/shared/components/template/components/combo-box/combo-box-modal/combo-box-modal.component.ts
  src/app/shared/components/template/components/combo-box/combo-box.component.ts
  src/app/shared/components/template/components/radio-button-grid/radio-button-grid.component.ts
  src/app/shared/components/template/components/radio-group/radio-group.component.ts
  src/app/shared/utils/utils.ts
Labels: fix
