Repository IDEMSInternational/open-app-builder, pull requests merged in 2024-12, with the labels that each got.

#2531 feat!: template-level app config overrides
  packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/template.parser.spec.ts
  packages/scripts/src/commands/app-data/convert/processors/xlsxWorkbook.ts
  packages/scripts/src/commands/app-data/convert/utils/app-data-string.utils.ts
  src/app/shared/components/template/components/layout/popup/popup.component.ts
  src/app/shared/components/template/models/index.ts
  src/app/shared/components/template/services/template-metadata.service.ts
  src/app/shared/components/template/services/template-nav.service.ts
  src/app/shared/components/template/template-component.ts
  src/app/shared/components/template/template-container.component.html
  src/app/shared/components/template/template-container.component.ts
  src/app/shared/services/app-config/app-config.service.spec.ts
  src/app/shared/services/app-config/app-config.service.ts
  src/app/shared/services/screen-orientation/screen-orientation.service.ts
  src/app/shared/services/skin/skin.service.ts
Labels: feature, scripts, test - visual, test - preview

#2571 Feat(map): layer groups
  src/app/shared/components/template/components/map/map.component.html
  src/app/shared/components/template/components/map/map.component.scss
  src/app/shared/components/template/components/map/map.component.ts
Labels: feature, scripts

#2588 fix: template container error alt
  src/app/shared/components/template/template-container.component.ts
Labels: fix

#2587 feat(map): new layer property, 'excluded_features_colour'
  src/app/shared/components/template/components/map/map.component.ts
Labels: feature

#2558 Kuwait Theme: Progress Wheel
  src/app/shared/components/template/components/task-progress-bar/task-progress-bar.component.html
  src/app/shared/components/template/components/task-progress-bar/task-progress-bar.component.scss
  src/app/shared/components/template/components/task-progress-bar/task-progress-bar.component.ts
  src/theme/themes/plh_kids_kw/_overrides.scss
Labels: feature, test - preview

#2591 fix: progress-bar-component post-2558
  src/app/shared/components/template/components/task-progress-bar/task-progress-bar.component.ts
Labels: fix

#2596 Bug fix: Remove right aligned styling on text bubble
  src/theme/themes/plh_kids_kw/_overrides.scss
Labels: test - preview, fix

#2585 Kuwait Theme: Round Button Variants
  src/app/shared/components/template/components/round-icon-button/round-icon-button.component.html
  src/app/shared/components/template/components/round-icon-button/round-icon-button.component.scss
  src/app/shared/components/template/components/round-icon-button/round-icon-button.component.ts
  src/theme/themes/plh_kids_kw/_overrides.scss
Labels: test - preview

#2600 refactor: display group sticky component
  src/app/feature/nav-stack/components/nav-stack/nav-stack.component.global.scss
  src/app/shared/components/template/components/index.ts
  src/app/shared/components/template/components/layout/display-group/display-group.component.html
  src/app/shared/components/template/components/layout/display-group/display-group.component.scss
  src/app/shared/components/template/components/layout/display-group/display-group.component.ts
  src/app/shared/components/template/components/layout/display-group/sticky/display-group-sticky.component.html
  src/app/shared/components/template/components/layout/display-group/sticky/display-group-sticky.component.scss
  src/app/shared/components/template/components/layout/display-group/sticky/display-group-sticky.component.ts
  src/app/shared/components/template/components/manifest.ts
Labels: maintenance

#2564 feat: inline header or footer, via 'sticky' display group param
  src/app/feature/nav-stack/components/nav-stack/nav-stack.component.html
  src/app/feature/nav-stack/components/nav-stack/nav-stack.component.ts
  src/app/feature/nav-stack/nav-stack.actions.ts
  src/app/shared/components/template/components/index.ts
  src/app/shared/components/template/components/layout/display-group/display-group.component.html
  src/app/shared/components/template/components/layout/display-group/display-group.component.ts
  src/app/shared/components/template/components/layout/display-group/sticky/display-group-sticky.component.html
  src/app/shared/components/template/components/layout/display-group/sticky/display-group-sticky.component.scss
  src/app/shared/components/template/components/layout/display-group/sticky/display-group-sticky.component.ts
  src/app/shared/components/template/components/manifest.ts
  src/app/shared/components/template/components/title.ts
  src/app/shared/components/template/components/title/title.component.html
  src/app/shared/components/template/components/title/title.component.scss
  src/app/shared/components/template/components/title/title.component.ts
  src/app/shared/components/template/template-component.scss
  src/theme/variables.scss
Labels: feature, test - preview

#2605 fix: audio modal close trigger
  src/app/shared/components/template/components/audio/audio.component.ts
Labels: fix

#2608 fix: sticky header position
  src/app/shared/components/template/components/layout/display-group/sticky/display-group-sticky.component.scss
  src/app/shared/components/template/components/layout/display-group/sticky/display-group-sticky.component.ts
Labels: fix

#2597 Fix: parameter list dynamic keys
  packages/scripts/src/commands/app-data/convert/processors/flowParser/flowParser.ts
  packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/default.parser.ts
  packages/scripts/src/commands/app-data/convert/utils/app-data-string.utils.ts
  src/app/shared/components/template/services/template-field.service.spec.ts
  src/app/shared/components/template/services/template-variables.service.spec.ts
  src/app/shared/components/template/services/template-variables.service.ts
  src/app/shared/services/data/app-data.service.mock.spec.ts
  src/app/shared/services/data/app-data.service.spec.ts
  src/app/shared/services/data/app-data.service.ts
  src/app/shared/services/dynamic-data/adapters/persistedMemory.ts
  src/app/shared/services/dynamic-data/dynamic-data.actions.spec.ts
  src/app/shared/services/dynamic-data/dynamic-data.service.spec.ts
  src/app/shared/services/dynamic-data/dynamic-data.service.ts
  src/app/shared/services/task/task.service.spec.ts
Labels: scripts, test - preview, fix

#2568 refactor: data items logic separation
  src/app/shared/components/template/components/base.ts
  src/app/shared/components/template/components/data-items/data-items.component.html
  src/app/shared/components/template/components/data-items/data-items.component.spec.ts
  src/app/shared/components/template/components/data-items/data-items.component.ts
  src/app/shared/components/template/components/data-items/data-items.service.spec.ts
  src/app/shared/components/template/components/data-items/data-items.service.ts
  src/app/shared/components/template/components/data-items/data-items.utils.spec.ts
  src/app/shared/components/template/components/data-items/data-items.utils.ts
  src/app/shared/components/template/components/layout/workshops_accordion.ts
  src/app/shared/components/template/template-component.ts
  src/app/shared/services/dynamic-data/dynamic-data.service.mock.spec.ts
  src/app/shared/services/dynamic-data/dynamic-data.service.ts
Labels: test - preview

#2599 feat: 'nav: back' and 'nav: forward' template actions
  packages/data-models/flowTypes.ts
  src/app/shared/components/template/services/template-nav.service.ts
Labels: feature

#2614 fix: sticky display group custom styles
  src/app/shared/components/template/components/layout/display-group/sticky/display-group-sticky.component.scss
Labels: test - preview, fix

#2633 fix: dynamic data for data list including app metadata fields
  src/app/shared/services/dynamic-data/adapters/reactiveMemory.ts
  src/app/shared/services/dynamic-data/dynamic-data.service.ts
Labels: fix

#2632 chore: add conflict_forecast theme
  src/theme/themes/_index.scss
  src/theme/themes/conflict_forecast.scss
  src/theme/variables.scss
Labels: maintenance

#2628 Bug Fix: Flip Module List Item nav-asset in RTL
  src/theme/themes/plh_kids_kw/_overrides.scss
Labels: test - preview, fix

#2629 Bug Fix: Accordion component responsiveness
  src/theme/themes/plh_kids_kw/_overrides.scss
Labels: test - preview, fix

#2627 Bug Fix: Select-Text RTL styling in kw theme
  src/app/shared/components/template/components/select-text/select-text.component.html
  src/app/shared/components/template/components/select-text/select-text.component.ts
  src/theme/themes/plh_kids_kw/_overrides.scss
Labels: test - preview, fix

#2625 Feat: add_data action
  package.json
  packages/data-models/flowTypes.ts
  src/app/shared/components/template/components/data-items/data-items.utils.ts
  src/app/shared/components/template/processors/itemPipe.ts
  src/app/shared/services/dynamic-data/actions/add_data.action.spec.ts
  src/app/shared/services/dynamic-data/actions/add_data.action.ts
  src/app/shared/services/dynamic-data/actions/index.ts
  src/app/shared/services/dynamic-data/actions/set_data.action.spec.ts
  src/app/shared/services/dynamic-data/actions/set_data.action.ts
  src/app/shared/services/dynamic-data/adapters/persistedMemory.ts
  src/app/shared/services/dynamic-data/adapters/reactiveMemory.ts
  src/app/shared/services/dynamic-data/dynamic-data.actions.ts
  src/app/shared/services/dynamic-data/dynamic-data.service.spec.ts
  src/app/shared/services/dynamic-data/dynamic-data.service.ts
  src/app/shared/utils/utils.ts
  yarn.lock
Labels: feature, test - preview

#2543 feat: apply item row operations, e.g. filter, on task progress bar data rows
  packages/shared/src/utils/object-utils.spec.ts
  packages/shared/src/utils/object-utils.ts
  src/app/shared/components/template/components/task-card/task-card.component.html
  src/app/shared/components/template/components/task-card/task-card.component.scss
  src/app/shared/components/template/components/task-card/task-card.component.ts
  src/app/shared/components/template/components/task-progress-bar/task-progress-bar.component.ts
  src/app/shared/components/template/processors/item.ts
  src/app/shared/components/template/processors/itemPipe.ts
Labels: feature

#2638 Feat: display grid data items
  src/app/shared/components/template/components/layout/display-grid/display-grid.component.html
  src/app/shared/components/template/components/layout/display-grid/display-grid.component.ts
Labels: feature

#2606 Kuwait Theme: Styling (Combo-box, Dashed-box, Task Card)
  src/app/shared/components/template/components/combo-box/combo-box.component.ts
  src/theme/themes/plh_kids_kw/_overrides.scss
Labels: test - preview, styling

#2639 fix: data items nested templates
  src/app/shared/components/template/components/data-items/data-items.service.ts
  src/app/shared/components/template/components/data-items/data-items.utils.ts
  src/app/shared/components/template/services/instance/template-row.service.ts
  src/app/shared/components/template/template-component.ts
  src/app/shared/components/template/template-container.component.html
  src/app/shared/components/template/template-container.component.ts
Labels: test - visual, fix

#2642 [FEATURE] Kuwait Theme - Completion Pop up variant
  src/app/shared/components/template/components/layout/popup/popup.component.html
  src/app/shared/components/template/components/layout/popup/popup.component.ts
  src/app/shared/components/template/services/template-nav.service.ts
  src/theme/themes/plh_kids_kw/_overrides.scss
Labels: feature

#2644 feat: add support for combo_box child data_items
  src/app/shared/components/template/components/combo-box/combo-box-modal/combo-box-modal.component.html
  src/app/shared/components/template/components/combo-box/combo-box-modal/combo-box-modal.component.ts
  src/app/shared/components/template/components/combo-box/combo-box.component.ts
  src/app/shared/components/template/components/data-items/data-items.service.ts
  src/app/shared/utils/utils.ts
Labels: feature

#2645 fix: rtl language config is applied to app launch templates
  src/app/shared/components/template/components/layout/popup/popup.component.html
  src/app/shared/components/template/components/layout/popup/popup.component.ts
Labels: fix

#2634 Refactor!: auth providers
  package.json
  packages/data-models/appConfig.ts
  packages/data-models/deployment.model.ts
  packages/scripts/src/tasks/providers/appData.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/deployment-features.module.ts
  src/app/shared/components/template/services/instance/template-action.service.ts
  src/app/shared/services/auth/auth.module.ts
  src/app/shared/services/auth/auth.service.ts
  src/app/shared/services/auth/providers/base.auth.ts
  src/app/shared/services/auth/providers/firebase.auth.ts
  src/app/shared/services/auth/providers/index.ts
  src/app/shared/services/auth/providers/supabase.auth.ts
  src/app/shared/services/auth/types.ts
  yarn.lock
Labels: scripts, breaking, maintenance

#2647 chore: data items nested templates review updates
  src/app/shared/components/template/components/data-items/data-items.utils.ts
  src/app/shared/components/template/template-component.ts
Labels: maintenance

#2648 refactor: header defaults and functions
  packages/data-models/appConfig.ts
  packages/data-models/skin.model.ts
  src/app/shared/components/header/header.component.ts
  src/app/shared/services/skin/skin.service.spec.ts
  src/app/shared/utils/angular.utils.ts
Labels: maintenance

#2631 feat!: expose additional header and footer configuration props to app config
  packages/data-models/appConfig.ts
  packages/data-models/skin.model.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/shared/components/header/header.component.html
  src/app/shared/components/header/header.component.ts
  src/app/shared/services/skin/skin.service.spec.ts
  src/app/shared/utils/angular.utils.ts
Labels: feature, test - preview

#2508 Kuwait Comp: Bottom Navbar
  packages/components/plh/index.ts
  packages/components/plh/plh-kids-kw/components/bottom-navigation-bar/bottom-navigation-bar.component.html
  packages/components/plh/plh-kids-kw/components/bottom-navigation-bar/bottom-navigation-bar.component.scss
  packages/components/plh/plh-kids-kw/components/bottom-navigation-bar/bottom-navigation-bar.component.spec.ts
  packages/components/plh/plh-kids-kw/components/bottom-navigation-bar/bottom-navigation-bar.component.ts
  packages/components/plh/plh-kids-kw/plh-kids-kw-routing.module.ts
  packages/components/plh/plh-kids-kw/plh-kids-kw.module.ts
  src/theme/themes/plh_kids_kw/_overrides.scss
Labels: feature, test - preview

#2661 fix: display group spacing RTL support
  src/app/shared/components/template/components/layout/display-group/display-group.component.scss
Labels: fix

#2657 chore: audio component handles RTL languages (LTR player controls enforced)
  src/app/shared/components/template/components/audio/audio.component.html
Labels: test - preview, maintenance

#2658 fix: text wrapping in title component for RTL languages
  src/app/shared/components/template/components/title/title.component.ts
Labels: test - preview, fix

#2656 Feat: nav stack back native
  src/app/feature/nav-stack/nav-stack-back.service.ts
  src/app/feature/nav-stack/nav-stack.module.ts
  src/app/feature/nav-stack/nav-stack.service.spec.ts
  src/app/feature/nav-stack/nav-stack.service.ts
Labels: feature

#2660 fix: pop-up close button position for RTL languages
  src/app/shared/components/template/components/layout/popup/popup.component.html
  src/app/shared/components/template/components/layout/popup/popup.component.scss
Labels: test - preview, fix
