Repository IDEMSInternational/open-app-builder, pull requests merged in 2024-03, with the labels that each got.

#2221 fix: data-items cdr
  src/app/shared/components/template/template-container.component.ts
Labels: fix

#2223 fix: cdr injection
  src/app/shared/components/template/template-container.component.ts
  tsconfig.json
Labels: fix

#2226 refactor: header collapse implementation
  packages/data-models/appConfig.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/feature/template/template.page.html
  src/app/feature/template/template.page.ts
  src/app/shared/components/common/directives/collapse-on-scroll.directive.spec.ts
  src/app/shared/components/common/directives/collapse-on-scroll.directive.ts
  src/app/shared/components/header/header.component.html
  src/app/shared/components/header/header.component.scss
  src/app/shared/components/header/header.component.ts
Labels: maintenance

#2227 feat: add 3 new variants for display group: box_gray, box_primary, box_secondary
  src/app/shared/components/template/components/index.ts
  src/app/shared/components/template/components/layout/display-group/display-group.component.html
  src/app/shared/components/template/components/layout/display-group/display-group.component.scss
  src/app/shared/components/template/components/layout/display-group/display-group.component.ts
  src/app/shared/components/template/components/layout/display_group.ts
Labels: feature

#2216 feat: header config: 'collapsing', 'compact, and 'colour' options
  packages/data-models/appConfig.ts
  src/app/app.component.ts
  src/app/feature/template/template.page.html
  src/app/feature/template/template.page.ts
  src/app/shared/components/header/header.component.html
  src/app/shared/components/header/header.component.scss
  src/app/shared/components/header/header.component.ts
  src/app/shared/components/plh-main-header.ts
  src/app/shared/components/template/components/drawer/drawer.component.scss
  src/app/shared/components/template/components/drawer/drawer.component.ts
  src/app/shared/shared.module.ts
  src/theme/themes/pfr.scss
  src/theme/variables.scss
Labels: feature

#2230 chore: update Firebase BoM; refactor: auth actions
  android/app/build.gradle
  packages/data-models/flowTypes.ts
  src/app/shared/components/template/services/instance/template-action.service.ts
  src/app/shared/services/auth/auth.service.ts
Labels: maintenance

#2251 feat: env-replace workspace
  packages/@idemsInternational/env-replace/.gitignore
  packages/@idemsInternational/env-replace/README.md
  packages/@idemsInternational/env-replace/package.json
  packages/@idemsInternational/env-replace/src/index.spec.ts
  packages/@idemsInternational/env-replace/src/index.ts
  packages/@idemsInternational/env-replace/test/child/.template.env
  packages/@idemsInternational/env-replace/test/test_basic.template.json
  packages/@idemsInternational/env-replace/tsconfig.json
  packages/@idemsInternational/env-replace/tsconfig.spec.json
  yarn.lock
Labels: feature

#2220 feat: add data-items eval context fields
  packages/data-models/flowTypes.ts
  src/app/shared/components/template/components/data-items/data-items.component.ts
  src/app/shared/components/template/processors/item.ts
  src/app/shared/components/template/services/instance/template-row.service.ts
Labels: feature

#2252 Feat!: templated android config
  .github/workflows/reusable-android-build.yml
  .github/workflows/reusable-app-build.yml
  .github/workflows/reusable-content-sync.yml
  android/.gitignore
  android/app/build.template.gradle
  android/app/src/main/AndroidManifest.template.xml
  android/app/src/main/assets/capacitor.config.json
  android/templates/MainActivity.template.java
  android/templates/strings.template.xml
  capacitor.config.template.ts
  documentation/docs/developers/android-assets.md
  documentation/docs/developers/in-app-updates.md
  packages/@idemsInternational/env-replace/src/index.ts
  packages/data-models/deployment.model.ts
  packages/scripts/package.json
  packages/scripts/src/commands/version.ts
  packages/scripts/src/tasks/providers/android.ts
  packages/shared/src/paths.ts
  packages/workflows/src/android.workflows.ts
  yarn.lock
Labels: documentation, breaking

#2250 fix: disable broken header collapse on ios
  src/app/feature/template/template.page.html
  src/app/feature/template/template.page.ts
  src/app/shared/components/header/header.component.ts
Labels: fix
