Repository IDEMSInternational/open-app-builder, pull requests merged in 2024-05, with the labels that each got.

#2308 refactor: data-pipe parse string
  packages/shared/src/models/appStringEvaluator/appStringEvaluator.spec.ts
  packages/shared/src/models/appStringEvaluator/appStringEvaluator.ts
  packages/shared/src/models/dataPipe/operators/appendColumns.spec.ts
  packages/shared/src/models/dataPipe/operators/appendColumns.ts
  packages/shared/src/utils/string-utils.spec.ts
  packages/shared/src/utils/string-utils.ts
Labels: maintenance

#2307 fix: data pipe append_columns operation can handle boolean strings
  packages/scripts/src/commands/app-data/convert/processors/flowParser/flowParser.ts
  packages/shared/src/models/dataPipe/operators/appendColumns.spec.ts
  packages/shared/src/models/dataPipe/operators/appendColumns.ts
  packages/shared/src/utils/string-utils.spec.ts
  packages/shared/src/utils/string-utils.ts
Labels: fix

#2309 fix: set_item actions nested inside item loop
  src/app/shared/components/template/components/data-items/data-items.component.spec.ts
  src/app/shared/components/template/components/data-items/data-items.component.ts
Labels: fix

#2296 Feat: user dynamic_data sync and import
  packages/api/spec-export.json
  packages/api/src/app.module.ts
  packages/api/src/db/migrations/007-dynamic-data-user-field.ts
  packages/api/src/endpoints/app_users/app_user.controller.ts
  packages/api/src/endpoints/app_users/app_user.model.ts
  packages/api/src/endpoints/app_users/app_user.service.ts
  packages/api/src/endpoints/app_users/dto/set-user-data.dto.ts
  packages/api/src/endpoints/contact_fields/contact_field.controller.ts
  src/app/app-routing.module.ts
  src/app/feature/user/pages/user-debug/user-debug.page.html
  src/app/feature/user/pages/user-debug/user-debug.page.scss
  src/app/feature/user/pages/user-debug/user-debug.page.ts
  src/app/feature/user/user.module.ts
  src/app/shared/services/dynamic-data/adapters/persistedMemory.ts
  src/app/shared/services/dynamic-data/dynamic-data.service.ts
  src/app/shared/services/server/server.service.ts
  src/app/shared/services/userMeta/userMeta.service.ts
Labels: test - preview

#2302 fix: ios button card style issue
  src/app/shared/components/template/components/button/button.component.scss
Labels: test - visual, fix

#2288 fix: iOS popup close button behaviour
  packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/default.parser.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/shared/components/template/components/navigation-bar/navigation-bar.component.scss
  src/global.scss
  src/theme/overrides.ios.scss
Labels: fix

#2312 fix: data items are sorted according to original order by default
  src/app/shared/services/dynamic-data/adapters/persistedMemory.ts
  src/app/shared/services/dynamic-data/adapters/reactiveMemory.ts
  src/app/shared/services/dynamic-data/dynamic-data.service.spec.ts
  src/app/shared/services/dynamic-data/dynamic-data.service.ts
Labels: fix

#2317 feat: add support for RTL languages
  packages/data-models/appConfig.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/shared/components/template/services/template-translate.service.ts
Labels: feature
