Repository IDEMSInternational/open-app-builder, pull requests merged in 2024-06, with the labels that each got.

#2323 fix: data-items underscore properties
  src/app/shared/services/dynamic-data/dynamic-data.service.spec.ts
  src/app/shared/services/dynamic-data/dynamic-data.service.ts
Labels: fix

#2332 docs: replace all references to "parenting-app-ui" in the docs with "open-app-builder", including links to online documentation site
  README.md
  documentation/docs/authors/advanced/overrides.md
  documentation/docs/authors/notifications.md
  documentation/docs/developers/deployments.md
  documentation/docs/developers/device-testing.md
  documentation/docs/developers/in-app-updates.md
  documentation/docs/developers/web-previews.md
  documentation/docs/index.md
  documentation/docs/questions/parameters_styles.md
  documentation/mkdocs.yml
Labels: documentation

#2331 chore: add localstorage undefined handling
  src/app/shared/services/local-storage/local-storage.service.ts
Labels: maintenance

#2342 fix: data pipe merge operator handles case of no input source
  packages/shared/src/models/dataPipe/operators/filter.spec.ts
  packages/shared/src/models/dataPipe/operators/merge.spec.ts
  packages/shared/src/models/dataPipe/operators/merge.ts
Labels: fix
