Repository IDEMSInternational/open-app-builder, pull requests merged in 2025-06, with the labels that each got.

#2980 Fix: Apple auth
  ios/App/Podfile
  ios/App/Podfile.lock
  src/app/shared/services/auth/providers/firebase.auth.ts
  src/app/shared/services/error-handler/error-handler.service.ts
Labels: fix

#2982 Chore: set data optimisation alt
  src/app/shared/services/dynamic-data/actions/set_data.action.spec.ts
  src/app/shared/services/dynamic-data/actions/set_data.action.ts
  src/app/shared/services/dynamic-data/dynamic-data.service.ts
  src/app/shared/services/dynamic-data/dynamic-data.utils.spec.ts
  src/app/shared/services/dynamic-data/dynamic-data.utils.ts
Labels: maintenance

#2985 Feat: Task Progress Bar parameter to override progress percentage
  src/app/shared/components/template/components/task-progress-bar/task-progress-bar.component.html
  src/app/shared/components/template/components/task-progress-bar/task-progress-bar.component.ts
Labels: feature

#2991 fix!: shared data on iOS (alt implementation)
  android/app/capacitor.build.gradle
  android/app/src/main/assets/capacitor.plugins.json
  android/capacitor.settings.gradle
  ios/App/Podfile
  ios/App/Podfile.lock
  package.json
  src/app/app.component.ts
  src/app/feature/shared-data/providers/firebase.ts
  src/app/shared/services/auth/providers/firebase.auth.ts
  yarn.lock
Labels: fix, breaking

#2993 Feat: notification actions
  packages/data-models/fields.ts
  packages/data-models/flowTypes.ts
  packages/shared/src/models/jsEvaluator/jsEvaluator.ts
  src/app/feature/campaign/campaign.service.ts
  src/app/feature/notification/README.md
  src/app/feature/notification/notification.actions.ts
  src/app/feature/notification/notification.module.ts
  src/app/feature/notification/notification.service.spec.ts
  src/app/feature/notification/notification.service.ts
  src/app/feature/notification/notification.types.ts
  src/app/feature/notification/pages/notifications-debug/notifications-debug.page.ts
  src/app/shared/services/notification/local-notification-persist.adapter.ts
  src/app/shared/services/notification/local-notification.service.ts
Labels: feature, test - preview

#2971 [STYLING] MaPa theme style overrides
  src/theme/themes/plh_facilitator_mapa/_index.scss
  src/theme/themes/plh_facilitator_mapa/_overrides.scss
Labels: styling
