Repository IDEMSInternational/open-app-builder, pull requests merged in 2025-08, with the labels that each got.

#3072 fix: task card progress
  src/app/shared/components/template/components/progress-path/progress-path.component.ts
  src/app/shared/components/template/components/task-card/task-card.component.html
  src/app/shared/components/template/components/task-progress-bar/task-progress-bar.component.ts
Labels: test - preview, fix

#3059 feat: add android legacy compatibility check
  .browserslistrc
  .eslintrc.json
  android/app/src/main/java/utils/WebViewChecker.java
  android/templates/MainActivity.template.java
Labels: feature

#3083 chore: progress path component handles data_items child content, plh_progress_path components
  src/app/shared/components/template/components/progress-path/progress-path.component.html
  src/app/shared/components/template/components/progress-path/progress-path.component.scss
  src/app/shared/components/template/components/progress-path/progress-path.component.spec.ts
  src/app/shared/components/template/components/progress-path/progress-path.component.ts
Labels: maintenance

#3108 Feat: shared data static queries
  packages/components/plh/parent-group/plh-parent-group.service.ts
  src/app/feature/shared-data/providers/base.ts
  src/app/feature/shared-data/providers/firebase.ts
Labels: feature

#3115 fix: radio-button-grid text wrapping
  src/app/shared/components/template/components/radio-button-grid/radio-button-grid.component.scss
Labels: fix

#3109 style: remove additional padding around pop-up content for fullscreen pop-ups
  src/app/shared/components/template/components/layout/popup/popup.component.scss
Labels: test - preview

#3123 style: remove excess top margin on text-area component
  src/app/shared/components/template/components/text-area/text-area.component.html
Labels: test - preview

#3125 Fix: audio component styling
  src/app/shared/components/template/components/audio/audio.component.html
  src/theme/themes/plh_facilitator_mx/_overrides.scss
  src/theme/themes/plh_facilitator_my/overrides.scss
  src/theme/themes/plh_facilitator_ph/_overrides.scss
  src/theme/themes/plh_kids_kw/_overrides.scss
  src/theme/themes/plh_kids_tz/_index.scss
  src/theme/themes/plh_kids_tz/_overrides.scss
Labels: test - preview, fix
