Repository IDEMSInternational/open-app-builder, pull requests merged in 2025-04, with the labels that each got.

#2890 chore(deps): update ionic to v8
  .browserslistrc
  angular.json
  package.json
  src/app/app.component.spec.ts
  src/app/app.module.ts
  src/app/feature/campaign/pages/campaign-debug/campaign-debug.page.html
  src/app/feature/campaign/pages/campaign-debug/components/campaign-variables-editor.ts
  src/app/feature/feedback/components/feedback-toolbar/feedback-toolbar.component.html
  src/app/feature/feedback/components/feedback-toolbar/feedback-toolbar.component.scss
  src/app/feature/user/pages/user-debug/user-debug.page.html
  src/app/shared/components/template/components/simple-checkbox/simple-checkbox.component.html
  src/app/shared/components/template/components/simple-checkbox/simple-checkbox.component.scss
  src/app/shared/components/template/components/timer/timer.component.ts
  src/app/shared/components/template/components/toggle-bar/toggle-bar.html
  src/app/shared/services/audio/audio.recording.service.ts
  src/app/shared/services/audio/ionic.audio.player.ts
  src/app/shared/services/notification/push-notification.service.ts
  yarn.lock
Labels: test - visual, test - preview, maintenance

#2900 chore(deps): angular minor update
  package.json
  yarn.lock
Labels: maintenance

#2891 Chore(api): dep updates
  documentation/docs/developers/server-development.md
  packages/api/.env.example
  packages/api/.eslintrc.js
  packages/api/Dockerfile
  packages/api/eslint.config.mjs
  packages/api/package.json
  packages/api/spec-export.json
  packages/api/src/db/index.ts
  packages/api/src/endpoints/app_notification_interaction/app_notification_interaction.controller.ts
  packages/api/src/endpoints/app_notification_interaction/app_notification_interaction.e2e.spec.ts
  packages/api/src/endpoints/app_notification_interaction/app_notification_interaction.service.ts
  packages/api/src/endpoints/app_users/app_user.controller.ts
  packages/api/src/endpoints/app_users/app_user.e2e.spec.ts
  packages/api/src/endpoints/auth_users/auth_user.controller.ts
  packages/api/src/endpoints/auth_users/index.ts
  packages/api/src/endpoints/common/app.dto.ts
  packages/api/src/endpoints/contact_fields/contact_field.e2e.spec.ts
  packages/api/src/endpoints/contact_fields/contact_field.service.ts
  packages/api/src/endpoints/index.ts
  packages/api/src/endpoints/tables/tables.controller.ts
  packages/api/src/endpoints/tables/tables.middleware.ts
  packages/api/src/endpoints/tables/tables.service.ts
  packages/api/src/environment/index.ts
  packages/api/src/main.ts
  packages/api/src/modules/deployment.decorators.ts
  packages/api/src/modules/deployment.e2e.spec.ts
  packages/api/src/modules/deployment.module.ts
  packages/api/src/modules/deployment.service.ts
  packages/api/test/.test.env
  packages/api/test/test.utils.ts
  packages/api/tsconfig.json
  packages/server/docker/docker-compose.yml
  yarn.lock
Labels: documentation, maintenance

#2879 Feat: Combo box search filter
  src/app/shared/components/template/components/combo-box/combo-box-search/combo-box-search.component.html
  src/app/shared/components/template/components/combo-box/combo-box-search/combo-box-search.component.scss
  src/app/shared/components/template/components/combo-box/combo-box-search/combo-box-search.component.ts
  src/app/shared/components/template/components/combo-box/combo-box.component.html
  src/app/shared/components/template/components/combo-box/combo-box.component.scss
  src/app/shared/components/template/components/combo-box/combo-box.component.ts
  src/app/shared/components/template/components/index.ts
Labels: feature, test - preview

#2887 fix: local vars defined in data-items only support string type
  src/app/shared/components/template/components/data-items/data-items.service.spec.ts
  src/app/shared/components/template/components/data-items/data-items.service.ts
Labels: test - preview, fix

#2907 fix: template-injection-context
  src/app/shared/components/template/services/instance/template-process.service.ts
  src/app/shared/components/template/template-container.component.ts
Labels: fix

#2901 Refactor: dynamic data
  packages/shared/src/utils/file-utils.ts
  packages/shared/src/utils/object-utils.spec.ts
  packages/shared/src/utils/object-utils.ts
  src/app/shared/components/template/components/data-items/data-items.service.ts
  src/app/shared/components/template/components/task-progress-bar/task-progress-bar.component.ts
  src/app/shared/services/dynamic-data/adapters/persistedMemory.ts
  src/app/shared/services/dynamic-data/dynamic-data.service.mock.spec.ts
  src/app/shared/services/dynamic-data/dynamic-data.service.spec.ts
  src/app/shared/services/dynamic-data/dynamic-data.service.ts
  src/app/shared/services/remote-asset/remote-asset.service.ts
  src/app/shared/utils/utils.ts
Labels: maintenance

#2902 Fix: dynamic data delete
  src/app/shared/services/dynamic-data/adapters/persistedMemory.ts
  src/app/shared/services/dynamic-data/adapters/reactiveMemory.ts
  src/app/shared/services/dynamic-data/dynamic-data.service.spec.ts
  src/app/shared/services/dynamic-data/dynamic-data.service.ts
Labels: fix

#2905 Feat: Add date time picker
  cspell.config.yml
  documentation/docs/assets/images/date-time-picker.png
  src/app/shared/components/template/components/base.ts
  src/app/shared/components/template/components/date-time-picker/date-time-picker.component.html
  src/app/shared/components/template/components/date-time-picker/date-time-picker.component.md
  src/app/shared/components/template/components/date-time-picker/date-time-picker.component.scss
  src/app/shared/components/template/components/date-time-picker/date-time-picker.component.spec.ts
  src/app/shared/components/template/components/date-time-picker/date-time-picker.component.ts
  src/app/shared/components/template/components/index.ts
Labels: documentation, feature

#2915 fix: data items external field
  src/app/shared/components/template/components/base.ts
Labels: fix

#2899 Feat: shared data
  cspell.config.yml
  packages/data-models/deployment.model.ts
  packages/data-models/flowTypes.ts
  packages/scripts/src/tasks/providers/appData.ts
  src/app/app-routing.module.ts
  src/app/deployment-features.module.ts
  src/app/feature/shared-data/README.md
  src/app/feature/shared-data/firestore.rules
  src/app/feature/shared-data/index.ts
  src/app/feature/shared-data/pages/debug/row-templates.ts
  src/app/feature/shared-data/pages/debug/shared-data-debug.page.html
  src/app/feature/shared-data/pages/debug/shared-data-debug.page.scss
  src/app/feature/shared-data/pages/debug/shared-data-debug.page.ts
  src/app/feature/shared-data/providers/base.ts
  src/app/feature/shared-data/providers/firebase.ts
  src/app/feature/shared-data/providers/index.ts
  src/app/feature/shared-data/shared-data.actions.ts
  src/app/feature/shared-data/shared-data.service.spec.ts
  src/app/feature/shared-data/shared-data.service.ts
  src/app/feature/shared-data/trackedBehaviorSubject.ts
  src/app/feature/shared-data/types.ts
  src/app/shared/components/template/components/index.ts
  src/app/shared/components/template/components/shared-data/shared-data.component.html
  src/app/shared/components/template/components/shared-data/shared-data.component.scss
  src/app/shared/components/template/components/shared-data/shared-data.component.spec.ts
  src/app/shared/components/template/components/shared-data/shared-data.component.ts
  src/app/shared/services/firebase/firebase.service.ts
Labels: feature, scripts
