Repository IDEMSInternational/open-app-builder, pull requests merged in 2025-09, with the labels that each got.

#3073 fix: delete account
  src/app/shared/services/auth/providers/firebase.auth.ts
Labels: test - preview, fix

#3116 Feat: plh bottom nav text hide
  packages/components/plh/plh-kids-kw/components/bottom-navigation-bar/bottom-navigation-bar.component.html
  packages/components/plh/plh-kids-kw/components/bottom-navigation-bar/bottom-navigation-bar.component.scss
  packages/components/plh/plh-kids-kw/components/bottom-navigation-bar/bottom-navigation-bar.component.ts
  src/theme/themes/plh_facilitator_mx/_overrides.scss
  src/theme/themes/plh_facilitator_my/overrides.scss
  src/theme/themes/plh_facilitator_ph/_overrides.scss
  src/theme/themes/plh_kids_kw/_overrides.scss
Labels: feature, test - preview

#3146 chore(deps): update ionic dependencies
  package.json
  yarn.lock
Labels: maintenance
