Repository IDEMSInternational/open-app-builder, pull requests merged in 2025-02, with the labels that each got.

#2727 fix: allow firebase auth to be enabled independent of crashlytics
  packages/data-models/deployment.model.ts
  src/app/shared/services/firebase/firebase.service.ts
Labels: fix

#2767 Refactor: eval context typing
  packages/components/plh/parent-point-box/parent-point-box.component.ts
  packages/data-models/flowTypes.ts
  packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/template.parser.ts
  src/app/feature/campaign/campaign.service.ts
  src/app/shared/components/template/components/audio/audio.component.ts
  src/app/shared/components/template/components/data-items/data-items.component.ts
  src/app/shared/components/template/components/data-items/data-items.service.spec.ts
  src/app/shared/components/template/components/data-items/data-items.utils.spec.ts
  src/app/shared/components/template/components/data-items/data-items.utils.ts
  src/app/shared/components/template/components/html/html.component.ts
  src/app/shared/components/template/components/layout/accordion-section/accordion-section.component.ts
  src/app/shared/components/template/components/lottie-animation.ts
  src/app/shared/components/template/components/select-text/select-text.component.ts
  src/app/shared/components/template/components/slider/slider.component.ts
  src/app/shared/components/template/components/text/text.component.ts
  src/app/shared/components/template/components/timer/timer.component.ts
  src/app/shared/components/template/pipes/plh-asset.pipe.ts
  src/app/shared/components/template/processors/item.ts
  src/app/shared/components/template/services/instance/template-action.service.ts
  src/app/shared/components/template/services/instance/template-row.service.ts
  src/app/shared/components/template/services/template-translate.service.ts
  src/app/shared/components/template/services/template-variables.service.spec.ts
  src/app/shared/components/template/services/template-variables.service.ts
  src/app/shared/services/remote-asset/remote-asset.service.spec.ts
Labels: scripts

#2771 Fix: ci screenshots
  .github/workflows/test-visual-generate.yml
  .github/workflows/test-visual.yml
  packages/test-e2e/package.json
  packages/test-visual/.env.sample
  packages/test-visual/package.json
  packages/test-visual/src/commands/download.ts
  packages/test-visual/src/commands/generate.ts
  packages/test-visual/src/config/index.ts
  packages/test-visual/src/config/test.ts
  packages/test-visual/src/helpers/github.ts
  packages/test-visual/src/index.ts
  packages/test-visual/src/utils/index.ts
  packages/test-visual/tsconfig.json
  yarn.lock
Labels: test - visual, fix

#2770 feat(map): display legend vertically
  src/app/shared/components/template/components/map/map.component.html
  src/app/shared/components/template/components/map/map.component.scss
  src/app/shared/components/template/components/map/map.component.ts
Labels: feature

#2773 style: new display group variant for MX button use case
  src/app/shared/components/template/components/layout/display-group/display-group.component.scss
  src/theme/themes/plh_facilitator_mx/_overrides.scss
Labels: test - preview

#2780 hotfix: data-items local variables
  src/app/shared/components/template/components/data-items/data-items.service.ts
  src/app/shared/components/template/services/instance/template-action.service.spec.ts
  src/app/shared/components/template/services/instance/template-action.service.ts
  src/app/shared/components/template/services/instance/template-process.service.ts
  src/app/shared/components/template/services/instance/template-row.service.ts
Labels: fix

#2748 chore: PLH Kids TZ theme
  src/theme/themes/_index.scss
  src/theme/themes/plh_kids_tz.scss
  src/theme/variables.scss
Labels: maintenance

#2781 feat(map): support multiple layers sharing the same scale
  src/app/shared/components/template/components/map/map.component.html
  src/app/shared/components/template/components/map/map.component.scss
  src/app/shared/components/template/components/map/map.component.ts
Labels: feature

#2783 fix(map): handle showing new layer with same scale_id
  src/app/shared/components/template/components/map/map.component.ts
Labels: fix

#2785 feat(conflict_forecast): table component
  package.json
  src/app/shared/components/template/components/index.ts
  src/app/shared/components/template/components/table/table.component.html
  src/app/shared/components/template/components/table/table.component.scss
  src/app/shared/components/template/components/table/table.component.spec.ts
  src/app/shared/components/template/components/table/table.component.ts
  src/app/shared/components/template/template.module.ts
  yarn.lock
Labels: feature

#2775 Chore: ng test ci and mock updates
  .github/workflows/web-build.yml
  package.json
  src/app/feature/theme/services/theme.service.mock.spec.ts
  src/app/feature/theme/services/theme.service.spec.ts
  src/app/shared/components/template/components/data-items/data-items.service.spec.ts
  src/app/shared/components/template/services/template-calc.service.mock.spec.ts
  src/app/shared/components/template/services/template-calc.service.spec.ts
  src/app/shared/components/template/services/template-calc.service.ts
  src/app/shared/components/template/services/template-variables.service.spec.ts
  src/app/shared/services/app-events/app-events.service.mock.spec.ts
  src/app/shared/services/data/app-data-variable.service.spec.ts
  src/app/shared/services/data/app-data.service.spec.ts
  src/app/shared/services/data/data-evaluation.service.mock.spec.ts
  src/app/shared/services/db/db.service.mock.spec.ts
  src/app/shared/services/db/db.service.spec.ts
  src/app/shared/services/local-storage/local-storage.service.mock.spec.ts
  src/app/shared/services/local-storage/local-storage.service.spec.ts
  src/app/shared/services/local-storage/local-storage.service.ts
  src/app/shared/services/skin/skin.service.spec.ts
  src/app/shared/services/userMeta/userMeta.service.ts
  yarn.lock
Labels: maintenance

#2789 chore(conflict_forecast): make table header sticky
  src/app/shared/components/template/components/table/table.component.html
  src/app/shared/components/template/components/table/table.component.scss
Labels: maintenance

#2794 chore(map): increase filter precision to 2 decimal places
  src/app/shared/components/template/components/map/map.component.ts
Labels: maintenance

#2768 Feat/share multiple
  src/app/shared/services/share/share.service.ts
Labels: test - preview

#2788 feat: Google Sign In button component
  src/app/shared/components/template/components/button-google-sign-in/button-google-sign-in.component.html
  src/app/shared/components/template/components/button-google-sign-in/button-google-sign-in.component.scss
  src/app/shared/components/template/components/button-google-sign-in/button-google-sign-in.component.ts
  src/app/shared/components/template/components/index.ts
Labels: feature

#2791 Feat: auth user data
  packages/data-models/fields.ts
  src/app/shared/services/auth/auth.service.ts
  src/app/shared/services/auth/providers/firebase.auth.ts
  src/app/shared/services/auth/providers/supabase.auth.ts
  src/app/shared/services/auth/types.ts
  src/app/shared/services/local-storage/local-storage.service.spec.ts
  src/app/shared/services/local-storage/local-storage.service.ts
  src/app/shared/services/server/server.service.ts
Labels: feature

#2793 refactor!: template-calc service
  src/app/shared/components/template/services/template-calc.service.mock.spec.ts
  src/app/shared/components/template/services/template-calc.service.spec.ts
  src/app/shared/components/template/services/template-calc.service.ts
Labels: breaking, maintenance

#2795 Feat!: auth restore data
  src/app/shared/services/auth/auth.service.ts
  src/app/shared/services/dynamic-data/dynamic-data.service.spec.ts
  src/app/shared/services/dynamic-data/dynamic-data.service.ts
  src/app/shared/services/userMeta/userMeta.service.ts
Labels: feature, test - preview, breaking

#2762 feat: add 'curved' variant for progress-path component
  src/app/shared/components/template/components/progress-path/progress-path.component.ts
Labels: feature, test - preview

#2737 [FEATURE] Kuwait Theme: Radio group styling
  src/app/shared/components/template/components/radio-button-grid/radio-button-grid.component.html
  src/app/shared/components/template/components/radio-button-grid/radio-button-grid.component.scss
  src/app/shared/components/template/components/radio-button-grid/radio-button-grid.component.ts
  src/theme/themes/early_family_math.scss
  src/theme/themes/pfr.scss
  src/theme/themes/plh_facilitator_mx/_index.scss
  src/theme/themes/plh_kids_kw/_index.scss
  src/theme/themes/plh_kids_kw/_overrides.scss
  src/theme/themes/plh_kids_tz.scss
  src/theme/themes/professional.scss
Labels: feature, test - preview

#2772 feat: data items local
  src/app/shared/components/template/components/data-items/data-items.component.ts
  src/app/shared/components/template/components/data-items/data-items.service.spec.ts
  src/app/shared/components/template/components/data-items/data-items.service.ts
  src/app/shared/components/template/components/data-items/data-items.utils.spec.ts
  src/app/shared/components/template/components/data-items/data-items.utils.ts
  src/app/shared/components/template/services/instance/template-row.service.ts
  src/app/shared/components/template/utils/template-utils.spec.ts
  src/app/shared/components/template/utils/template-utils.ts
Labels: feature, test - visual, test - preview

#2811 fix: auth restore profiles order
  src/app/shared/services/auth/auth.service.ts
Labels: fix

#2805 feat: plh_module_list_item highlighted param and circle variant
  packages/components/plh/plh-kids-kw/components/module-list-item/module-list-item.component.html
  packages/components/plh/plh-kids-kw/components/module-list-item/module-list-item.component.scss
  packages/components/plh/plh-kids-kw/components/module-list-item/module-list-item.component.ts
  src/theme/themes/plh_kids_kw/_index.scss
  src/theme/themes/plh_kids_kw/_overrides.scss
Labels: feature

#2806 feat: add user debug sidebar route
  src/app/app-routing.module.ts
Labels: feature, test - preview

#2816 fix: combo box visibility bug
  src/app/shared/components/template/components/combo-box/combo-box.component.html
  src/app/shared/components/template/components/combo-box/combo-box.component.ts
Labels: test - preview, fix

#2807 fix: data-items action value
  src/app/shared/components/template/services/instance/template-action.service.spec.ts
  src/app/shared/components/template/services/instance/template-action.service.ts
  src/app/shared/services/dynamic-data/actions/set_data.action.ts
  src/app/shared/services/dynamic-data/dynamic-data.service.ts
Labels: fix

#2815 refactor: store partial updates in dynamic data cache
  packages/shared/src/utils/object-utils.spec.ts
  packages/shared/src/utils/object-utils.ts
  src/app/feature/user/pages/user-debug/user-debug.page.ts
  src/app/shared/services/dynamic-data/dynamic-data.service.spec.ts
  src/app/shared/services/dynamic-data/dynamic-data.service.ts
Labels: maintenance
