Repository IDEMSInternational/open-app-builder, pull requests merged in 2025-01, with the labels that each got.

#2663 feat: data_items triggered actions
  packages/data-models/flowTypes.ts
  packages/scripts/src/commands/app-data/convert/processors/flowParser/flowParser.ts
  packages/scripts/src/commands/app-data/convert/utils/app-data-action.utils.ts
  src/app/shared/components/template/components/base.ts
  src/app/shared/components/template/components/data-items/data-items.component.ts
  src/app/shared/components/template/components/data-items/data-items.service.spec.ts
  src/app/shared/components/template/components/data-items/data-items.service.ts
Labels: feature, scripts

#2653 [STYLING] Kuwait Theme: Support added for accordion links
  src/theme/themes/plh_kids_kw/_overrides.scss
Labels: styling

#2604 Kuwait Theme: Custom styling for display-group 'box_*' variants
  src/theme/themes/plh_kids_kw/_overrides.scss
Labels: test - preview

#2562 Kuwait Theme: Activity Check-in component
  packages/components/plh/index.ts
  packages/components/plh/plh-kids-kw/components/activity-check-in/activity-check-in.component.html
  packages/components/plh/plh-kids-kw/components/activity-check-in/activity-check-in.component.scss
  packages/components/plh/plh-kids-kw/components/activity-check-in/activity-check-in.component.spec.ts
  packages/components/plh/plh-kids-kw/components/activity-check-in/activity-check-in.component.ts
  src/app/shared/components/template/components/number-selector/number-selector.component.ts
  src/app/shared/components/template/components/task-progress-bar/task-progress-bar.component.scss
Labels: feature, test - preview

#2589 Kuwait Theme: Add Background Image to Display Group
  src/app/feature/nav-stack/components/nav-stack/nav-stack.component.global.scss
  src/app/shared/components/template/components/layout/display-group/display-group.component.html
  src/app/shared/components/template/components/layout/display-group/display-group.component.scss
  src/app/shared/components/template/components/layout/display-group/display-group.component.ts
  src/app/shared/components/template/components/layout/display-group/sticky/display-group-sticky.component.scss
  src/app/shared/utils/utils.ts
Labels: test - preview

#2675 feat: button card-portrait variant handles disabled param; custom styling of button card-portrait variant for plh_kids_kw theme
  src/app/shared/components/template/components/button/button.component.html
  src/app/shared/components/template/components/button/button.component.scss
  src/app/shared/components/template/components/button/button.component.ts
  src/theme/themes/plh_kids_kw/_overrides.scss
Labels: feature

#2676 fix(plh-kids-kw): text-bubble speaker position for RTL language
  src/app/shared/components/template/components/text-bubble/text-bubble.component.scss
  src/theme/themes/plh_kids_kw/_overrides.scss
Labels: fix

#2598 Kuwait Theme: Settings page styling
  src/app/shared/components/template/components/button/button.component.html
  src/app/shared/components/template/components/button/button.component.ts
  src/app/shared/components/template/components/title/title.component.ts
  src/theme/themes/plh_kids_kw/_overrides.scss
Labels: test - preview, styling

#2679 fix: make button text alignment responsive to language direction
  src/app/shared/components/template/components/button/button.component.scss
  src/theme/deployment/_overrides.scss
  src/theme/themes/plh_kids_kw/_overrides.scss
Labels: test - preview, fix

#2682 chore(ios): update FirebaseCore cocoapods
  ios/App/Podfile
  ios/App/Podfile.lock
Labels: maintenance

#2683 fix: ios browser nav-stack height
  src/app/feature/nav-stack/components/nav-stack/nav-stack.component.global.scss
  src/theme/variables.scss
Labels: test - preview, fix

#2688 fix: iOS fullscreen popups
  src/app/feature/nav-stack/components/nav-stack/nav-stack.component.global.scss
  src/app/shared/components/template/components/layout/popup/popup.component.scss
Labels: test - preview, fix

#2691 fix: completion modal
  src/theme/themes/plh_kids_kw/_overrides.scss
Labels: fix

#2702 chore: handle MultiPolygon geometry type
  src/app/shared/components/template/components/map/map.component.ts
Labels: maintenance

#2671 feat: user profile restore
  src/app/feature/user/pages/user-debug/user-debug.page.html
  src/app/feature/user/pages/user-debug/user-debug.page.ts
  src/app/shared/services/auth/auth.service.ts
  src/app/shared/services/local-storage/local-storage.service.ts
  src/app/shared/services/server/server.service.ts
  src/app/shared/services/server/server.types.ts
  src/app/shared/services/userMeta/userMeta.service.ts
Labels: feature

#2703 feat(map): scale increments; change scale slider library
  package.json
  src/app/shared/components/template/components/map/map.component.html
  src/app/shared/components/template/components/map/map.component.scss
  src/app/shared/components/template/components/map/map.component.ts
  src/app/shared/components/template/template.module.ts
  yarn.lock
Labels: feature

#2706 fix: data-items set local
  packages/data-models/flowTypes.ts
  src/app/shared/components/template/components/base.ts
  src/app/shared/components/template/components/data-items/data-items.component.ts
  src/app/shared/components/template/components/data-items/data-items.service.ts
  src/app/shared/components/template/components/text-box/text-box.component.html
  src/app/shared/components/template/components/text/text.component.ts
  src/app/shared/components/template/services/instance/template-action.service.ts
Labels: fix

#2716 Mexico Theme: Refactor Theme-level Color Palette
  src/theme/themes/plh_facilitator_mx/_index.scss
  src/theme/themes/plh_facilitator_mx/_overrides.scss
  src/theme/themes/plh_facilitator_mx/_typography.scss
Labels: styling

#2715 feat: app language direction field
  packages/data-models/fields.ts
  src/app/shared/components/template/services/template-translate.service.ts
Labels: feature

#2701 fix: handle iOS safe area when app header is hidden (alt)
  src/app/app.component.html
  src/app/app.component.ts
  src/app/shared/components/header/header.component.html
  src/app/shared/components/header/header.component.scss
  src/app/shared/components/header/header.component.ts
Labels: fix

#2720 fix: app config page padding property is properly interpreted as shorthand
  src/app/app.component.ts
  src/app/shared/components/template/components/layout/display-group/display-group.component.scss
  src/app/shared/components/template/utils/render-utils.spec.ts
  src/app/shared/components/template/utils/render-utils.ts
  src/theme/deployment/_overrides.scss
Labels: fix

#2721 chore: make pr preview action secrets explicit
  .github/workflows/reusable-deploy-pr-preview.yml
Labels: maintenance

#2722 chore(ci): make deployment private key secret explicit in all relevant reusable workflows
  .github/workflows/reusable-android-build.yml
  .github/workflows/reusable-deploy-web-gh-pages.yml
  .github/workflows/reusable-deploy-web-preview.yml
Labels: maintenance

#2724 chore(ci): make deployment private key secret explicit in second-order workflows
  .github/workflows/reusable-android-release.yml
  .github/workflows/reusable-appetize.yml
  .github/workflows/reusable-content-sync.yml
Labels: maintenance

#2731 [FEATURE] Mexico Theme: Styling box-* variants
  src/theme/themes/plh_facilitator_mx/_overrides.scss
Labels: styling

#2730 [FEATURE] Mexico Theme: Icon button with text
  src/app/shared/components/template/components/button/button.component.html
  src/app/shared/components/template/components/button/button.component.ts
  src/theme/themes/plh_facilitator_mx/_index.scss
  src/theme/themes/plh_facilitator_mx/_overrides.scss
Labels: feature

#2719 chore: new 'dropdown' variant of combo-box
  src/app/shared/components/template/components/combo-box/combo-box.component.html
  src/app/shared/components/template/components/combo-box/combo-box.component.scss
  src/app/shared/components/template/components/combo-box/combo-box.component.ts
  src/theme/themes/plh_facilitator_mx/_index.scss
  src/theme/themes/plh_facilitator_mx/_overrides.scss
Labels: maintenance

#2743 Fix: MX accordion markdown styling
  src/theme/themes/plh_facilitator_mx/_overrides.scss
Labels: fix

#2739 chore: add title banner variants support to plh_facilitator_mx theme
  src/theme/themes/plh_facilitator_mx/_index.scss
  src/theme/themes/plh_facilitator_mx/_overrides.scss
Labels: maintenance

#2733 feat: combo-box component disabled state
  src/app/shared/components/template/components/combo-box/combo-box.component.html
  src/app/shared/components/template/components/combo-box/combo-box.component.scss
  src/app/shared/components/template/components/combo-box/combo-box.component.ts
Labels: feature

#2741 Fix: data items translations
  src/app/shared/components/template/components/data-items/data-items.service.spec.ts
  src/app/shared/components/template/components/data-items/data-items.service.ts
  src/app/shared/components/template/services/template-translate.service.spec.ts
  src/app/shared/components/template/services/template-translate.service.ts
  src/app/shared/services/data/app-data.service.mock.spec.ts
  src/app/shared/services/dynamic-data/dynamic-data.service.ts
Labels: test - preview, fix

#2747 fix: button card-portrait styling
  src/app/shared/components/template/components/button/button.component.html
Labels: fix

#2744 fix: combo-box dropdown variant emits 'changed' as expected
  src/app/shared/components/template/components/base.ts
  src/app/shared/components/template/components/combo-box/combo-box.component.html
  src/app/shared/components/template/components/combo-box/combo-box.component.ts
Labels: fix

#2698 [FEATURE] Kuwait theme: Map view progress path
  packages/components/plh/index.ts
  packages/components/plh/plh-kids-kw/components/plh-progress-path/plh-progress-path.component.html
  packages/components/plh/plh-kids-kw/components/plh-progress-path/plh-progress-path.component.scss
  packages/components/plh/plh-kids-kw/components/plh-progress-path/plh-progress-path.component.spec.ts
  packages/components/plh/plh-kids-kw/components/plh-progress-path/plh-progress-path.component.ts
  src/app/shared/components/template/components/task-card/task-card.component.html
  src/app/shared/components/template/components/task-card/task-card.component.scss
  src/app/shared/components/template/components/task-card/task-card.component.ts
  src/app/shared/components/template/utils/render-utils.ts
  src/app/shared/services/task/task.service.ts
  src/theme/themes/plh_kids_kw/_overrides.scss
Labels: feature

#2752 feat: MX theme button variant 'faq'
  src/theme/themes/plh_facilitator_mx/_overrides.scss
Labels: feature

#2736 [Bug Fix] Kuwait Theme: Center align list item text
  src/theme/themes/plh_kids_kw/_overrides.scss
Labels: test - preview, styling

#2758 fix: text box value bug
  src/app/shared/components/template/components/base.ts
Labels: fix

#2749 fix: action parameter self-references
  packages/scripts/src/commands/app-data/convert/processors/flowParser/flowParser.ts
  packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/template.parser.spec.ts
  packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/template.parser.ts
  src/app/shared/components/template/services/instance/template-action.service.spec.ts
  src/app/shared/components/template/services/instance/template-action.service.ts
Labels: scripts, fix

#2750 hotfix: action parameter self-reference concatenation
  src/app/shared/components/template/services/instance/template-action.service.spec.ts
  src/app/shared/components/template/services/instance/template-action.service.ts
Labels: scripts

#2760 Refactor: button disabled dynamic
  src/app/shared/components/template/components/button/button.component.html
  src/app/shared/components/template/components/button/button.component.ts
Labels: test - preview, maintenance

#2757 feat: make 'disabled' parameter of button component dynamic
  src/app/shared/components/template/components/button/button.component.html
  src/app/shared/components/template/components/button/button.component.ts
Labels: feature
