Repository IDEMSInternational/open-app-builder, pull requests merged in 2025-05, with the labels that each got.

#2920 fix: service init defer
  src/app/feature/shared-data/shared-data.service.ts
  src/app/shared/services/asyncService.base.ts
Labels: fix

#2924 fix: accordion style for kw-based themes
  src/theme/themes/plh_facilitator_mapa/_overrides.scss
  src/theme/themes/plh_facilitator_mx/_overrides.scss
  src/theme/themes/plh_kids_kw/_overrides.scss
Labels: test - preview, fix

#2428 core!: angular 18 update
  angular.json
  package.json
  packages/@idemsInternational/env-replace/package.json
  packages/@idemsInternational/gdrive-tools/package.json
  packages/@idemsInternational/rapidpro-excel/package.json
  packages/api/package.json
  packages/components/plh/parent-point-box/parent-point-box.component.spec.ts
  packages/data-models/package.json
  packages/scripts/package.json
  packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/default.parser.ts
  packages/shared/package.json
  packages/test-e2e/package.json
  packages/translations/package.json
  packages/workflows/package.json
  src/app/app.component.spec.ts
  src/app/app.module.ts
  src/app/feature/template/template.page.spec.ts
  src/app/shared/components/template/components/button/button.component.spec.ts
  src/app/shared/components/template/components/data-items/data-items.service.spec.ts
  src/app/shared/components/template/components/lottie-animation.ts
  src/app/shared/components/template/components/number-selector/number-selector.component.spec.ts
  src/app/shared/components/template/components/round-icon-button/round-icon-button.component.spec.ts
  src/app/shared/components/template/components/simple-checkbox/simple-checkbox.component.spec.ts
  src/app/shared/components/template/components/tile-component/tile-component.component.spec.ts
  src/app/shared/components/template/services/template-field.service.spec.ts
  src/app/shared/components/template/services/template-variables.service.spec.ts
  src/app/shared/components/template/template-container.component.spec.ts
  src/app/shared/components/template/template.module.ts
  src/app/shared/services/auth/auth.service.spec.ts
  src/app/shared/services/data/app-data.service.spec.ts
  src/app/shared/services/dynamic-data/actions/add_data.action.spec.ts
  src/app/shared/services/dynamic-data/actions/set_data.action.spec.ts
  src/app/shared/services/dynamic-data/dynamic-data.service.spec.ts
  src/app/shared/services/file-manager/file-manager.service.spec.ts
  src/app/shared/services/remote-asset/remote-asset.service.spec.ts
  src/app/shared/services/task/task.service.spec.ts
  yarn.lock
Labels: scripts, breaking

#2913 feat(Qol): Add google sheet folder URL to json
  packages/data-models/flowTypes.ts
  packages/scripts/src/commands/app-data/convert/processors/flowParser/flowParser.spec.ts
  packages/scripts/src/commands/app-data/convert/processors/flowParser/flowParser.ts
  packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/default.parser.ts
  packages/scripts/src/commands/app-data/convert/processors/xlsxWorkbook.ts
Labels: feature, scripts

#2917 Feat: Add combo box search close button
  src/app/shared/components/template/components/combo-box/combo-box-search/combo-box-search.component.html
  src/app/shared/components/template/components/combo-box/combo-box-search/combo-box-search.component.scss
  src/app/shared/components/template/components/combo-box/combo-box-search/combo-box-search.component.ts
  src/app/shared/components/template/components/combo-box/combo-box.component.ts
Labels: feature, test - preview

#2908 fix: ios build action
  .github/workflows/reusable-app-build.yml
  .github/workflows/reusable-ios-build.yml
Labels: fix

#2904 Feat: pdf viewer compatibility check
  angular.json
  package.json
  src/app/shared/components/template/components/pdf/pdf.component.html
  src/app/shared/components/template/components/pdf/pdf.component.spec.ts
  src/app/shared/components/template/components/pdf/pdf.component.ts
  src/app/shared/components/template/components/pdf/pdf.service.ts
  src/app/shared/utils/utils.ts
  yarn.lock
Labels: scripts, test - appetize

#2928 [FEATURE] Audio Player Styling - TZ theme
  src/theme/themes/plh_kids_tz/_index.scss
  src/theme/themes/plh_kids_tz/_overrides.scss
Labels: styling

#2910 feat(plh_facilitator): shared parent group functionality
  packages/components/plh/index.ts
  packages/components/plh/parent-group/plh-parent-group.actions.ts
  packages/components/plh/parent-group/plh-parent-group.module.ts
  packages/components/plh/parent-group/plh-parent-group.service.spec.ts
  packages/components/plh/parent-group/plh-parent-group.service.ts
  packages/data-models/flowTypes.ts
  src/app/deployment-features.module.ts
Labels: feature

#2929 [STYLING] TZ theme - Secondary button contrast
  src/theme/themes/plh_kids_tz/_overrides.scss
Labels: styling

#2885 Feat: adapt plh_progress_path component for plh_kids_tz application
  packages/components/plh/index.ts
  packages/components/plh/progress-path/progress-path.component.html
  packages/components/plh/progress-path/progress-path.component.scss
  packages/components/plh/progress-path/progress-path.component.spec.ts
  packages/components/plh/progress-path/progress-path.component.ts
  src/theme/themes/plh_kids_tz/_overrides.scss
Labels: feature, test - preview

#2940 [STYLING] TZ Theme: Round Navigation Button
  src/app/shared/components/template/components/button/button.component.ts
  src/theme/themes/plh_kids_tz/_index.scss
  src/theme/themes/plh_kids_tz/_overrides.scss
Labels: styling

#2933 [STYLING] TZ theme: Override Title and Button[card] styles
  src/theme/themes/plh_kids_tz/_overrides.scss
Labels: styling

#2939 Added disabled parameter to text-box and combo-box
  src/app/shared/components/template/components/combo-box/combo-box.component.ts
  src/app/shared/components/template/components/text-box/text-box.component.html
  src/app/shared/components/template/components/text-box/text-box.component.ts
Labels: test - preview

#2932 [STYLING] Refactor default text-bubble styling
  src/app/shared/components/template/components/text-bubble/text-bubble.component.scss
  src/theme/themes/default.scss
  src/theme/themes/plh_facilitator_mx/_index.scss
  src/theme/themes/plh_facilitator_mx/_overrides.scss
  src/theme/themes/plh_kids_kw/_index.scss
  src/theme/themes/plh_kids_kw/_overrides.scss
  src/theme/themes/plh_kids_tz/_index.scss
  src/theme/themes/utils/generate-theme.scss
  src/theme/variables.scss
Labels: styling

#2950 feat: add app env fields
  packages/data-models/fields.ts
  src/app/app.component.ts
Labels: feature, test - preview

#2946 Feat: Add scroll to top action
  packages/data-models/flowTypes.ts
  src/app/app.component.ts
  src/app/shared/services/scroll/scroll.service.spec.ts
  src/app/shared/services/scroll/scroll.service.ts
Labels: feature

#2953 [STYLING] TZ Theme: Module List Item
  packages/components/plh/module-list-item/module-list-item.component.scss
  src/theme/themes/plh_kids_kw/_overrides.scss
  src/theme/themes/plh_kids_tz/_index.scss
  src/theme/themes/plh_kids_tz/_overrides.scss
Labels: test - preview, styling

#2965 fix: handle numerical value passed to combo-box via field
  src/app/shared/components/template/components/combo-box/combo-box.component.ts
Labels: fix

#2970 [Mapa theme] Add round button colour overrides
  src/theme/themes/plh_facilitator_mapa/_index.scss
Labels: test - preview
