Repository IDEMSInternational/open-app-builder, pull requests merged in 2025-03, with the labels that each got.

#2830 fix: plh_kids_kw activity lock button position on ios
  src/theme/themes/plh_facilitator_mx/_overrides.scss
  src/theme/themes/plh_kids_kw/_overrides.scss
Labels: fix

#2831 docs: updates to Firebase config and auth
  documentation/docs/developers/deployments.md
Labels: documentation

#2822 chore: tidy server sync code
  packages/data-models/appConfig.ts
  packages/data-models/deployment.model.ts
  src/app/shared/components/template/services/instance/template-action.service.ts
  src/app/shared/services/db/db-sync.service.ts
  src/app/shared/services/server/server.service.ts
Labels: feature, breaking

#2837 feat: reusable-ios-build action
  .github/workflows/reusable-app-build.yml
  .github/workflows/reusable-ios-build.yml
  .prettierignore
Labels: feature

#2842 fix: ios visual bugs on elements with drop-shadow
  packages/components/plh/parent-point-box/parent-point-box.component.scss
  packages/components/plh/plh-kids-kw/components/module-list-item/module-list-item.component.scss
  src/app/shared/components/template/components/button/button.component.scss
  src/app/shared/components/template/components/task-card/task-card.component.scss
  src/theme/overrides.ios.scss
Labels: test - visual, fix

#2808 Refactor: value changed actions
  packages/components/plh/parent-point-box/parent-point-box.component.ts
  src/app/shared/components/template/components/base.ts
  src/app/shared/components/template/components/combo-box/combo-box.component.ts
  src/app/shared/components/template/components/number-selector/number-selector.component.ts
  src/app/shared/components/template/components/odk-form/odk-form.component.ts
  src/app/shared/components/template/components/radio-button-grid/radio-button-grid.component.ts
  src/app/shared/components/template/components/radio-group/radio-group.component.ts
  src/app/shared/components/template/components/simple-checkbox/simple-checkbox.component.ts
  src/app/shared/components/template/components/slider/slider.component.ts
  src/app/shared/components/template/components/text-area/text-area.component.ts
  src/app/shared/components/template/components/text-box/text-box.component.ts
  src/app/shared/components/template/components/toggle-bar/toggle-bar.ts
Labels: maintenance

#2850 fix: task card badge not-started
  src/app/shared/components/template/components/task-card/task-card.component.scss
Labels: fix

#2847 Fix: plh_progress_path component styling
  packages/components/plh/plh-kids-kw/components/plh-progress-path/plh-progress-path.component.scss
  src/theme/themes/plh_kids_kw/_overrides.scss
Labels: fix, styling

#2835 fix: firebase auth issues on ios
  src/app/shared/services/auth/providers/firebase.auth.ts
Labels: test - preview, test - appetize

#2839 feat: user debug page dynamic updates
  src/app/feature/user/pages/user-debug/user-debug.page.html
  src/app/feature/user/pages/user-debug/user-debug.page.scss
  src/app/feature/user/pages/user-debug/user-debug.page.ts
  src/app/shared/services/dynamic-data/adapters/persistedMemory.ts
Labels: feature

#2854 chore: rename some app config properties; add deprecation migration system
  packages/data-models/appConfig.ts
  src/app/app.component.html
  src/app/shared/components/header/header.component.html
  src/app/shared/components/header/header.component.scss
  src/app/shared/services/app-config/app-config.service.spec.ts
  src/app/shared/services/app-config/app-config.service.ts
  src/app/shared/services/skin/skin.service.spec.ts
Labels: test - preview, maintenance

#2862 feat: include firebase google auth requirements in ios configure workflow
  documentation/docs/developers/building-and-deploying-to-ios.md
  ios/App/App.xcodeproj/project.template.pbxproj
  ios/App/App/Info.plist
  ios/App/Podfile
  ios/App/Podfile.lock
  packages/@idemsInternational/env-replace/src/index.ts
  packages/scripts/package.json
  packages/scripts/src/tasks/providers/ios.ts
  packages/shared/src/paths.ts
  packages/workflows/src/ios.workflows.ts
  yarn.lock
Labels: documentation, feature, scripts

#2836 fix: android build lfs and debug signing
  .github/workflows/reusable-android-build.yml
Labels: fix

#2859 feat(campaigns): provide config for opt-out
  packages/data-models/deployment.model.ts
  packages/scripts/src/tasks/providers/appData.ts
  src/app/app.component.ts
  src/app/deployment-features.module.ts
  src/app/feature/campaign/campaign.module.ts
  src/app/feature/campaign/campaign.service.ts
  src/app/feature/campaign/pages/campaign-debug/campaign-debug.page.ts
  src/app/feature/notification/pages/notifications-debug/components/notification-debug-interacted-row.component.ts
  src/app/feature/notification/pages/notifications-debug/components/notification-debug-row.component.ts
  src/app/feature/notification/pages/notifications-debug/notifications-debug.page.html
  src/app/feature/notification/pages/notifications-debug/notifications-debug.page.spec.ts
  src/app/feature/notification/pages/notifications-debug/notifications-debug.page.ts
  src/app/shared/components/template/services/instance/template-action.service.ts
  src/app/shared/services/db/db.service.ts
  src/app/shared/services/notification/local-notification-persist.adapter.ts
  src/app/shared/services/notification/local-notification.service.ts
Labels: feature, scripts, test - preview

#2875 feat: add 'platform' protected field
  packages/data-models/fields.ts
  src/app/app.component.ts
Labels: feature, test - preview

#2869 Feat: apple auth
  capacitor.config.template.ts
  ios/.gitignore
  ios/App/App/App.entitlements
  packages/data-models/deployment.model.ts
  src/app/shared/services/auth/auth.service.ts
  src/app/shared/services/auth/providers/base.auth.ts
  src/app/shared/services/auth/providers/firebase.auth.ts
Labels: feature, test - preview, test - appetize
