Repository IDEMSInternational/open-app-builder, pull requests merged in 2025-07, with the labels that each got.

#3001 feat: add gemini codeassist config
  .gemini/config.yaml
  .gemini/styleguide.md
Labels: feature

#3028 fix: import user dynamic data including user-created rows
  packages/shared/src/utils/object-utils.spec.ts
  packages/shared/src/utils/object-utils.ts
  src/app/shared/services/dynamic-data/dynamic-data.service.mock.spec.ts
  src/app/shared/services/dynamic-data/dynamic-data.service.ts
  src/app/shared/services/userMeta/userMeta.service.spec.ts
  src/app/shared/services/userMeta/userMeta.service.ts
Labels: test - preview, fix

#3009 feat: authored notification interaction tracking
  src/app/app.component.ts
  src/app/deployment-features.module.ts
  src/app/feature/notification/notification.module.ts
  src/app/feature/notification/notification.service.spec.ts
  src/app/feature/notification/notification.service.ts
  src/app/feature/notification/notification.types.ts
  src/app/feature/user/pages/user-debug/user-debug.page.ts
  src/app/shared/services/capacitor-event/capacitor-event.mock.spec.ts
  src/app/shared/services/capacitor-event/capacitor-event.service.ts
  src/app/shared/services/notification/local-notification.service.ts
Labels: feature, test - preview

#3008 Fix(!): display group variable hoisting
  packages/scripts/src/commands/app-data/convert/processors/flowParser/flowParser.ts
  packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/template.parser.spec.ts
  packages/scripts/src/commands/app-data/convert/processors/flowParser/parsers/template.parser.ts
Labels: scripts, fix

#3036 Added actions, translations and system architecture to website documentation
  documentation/docs/authors/actions.md
  documentation/docs/authors/translations.md
  documentation/docs/system/diagrams.md
  documentation/docs/system/images/creating-app-diagram.png
  documentation/docs/system/images/running-app-diagram.png
  documentation/docs/system/technologies.md
  documentation/mkdocs.yml
Labels: documentation

#3006 feat: translate local var from default language to specified language when setting
  src/app/shared/components/template/services/instance/template-row.service.ts
  src/app/shared/components/template/services/template-translate.service.ts
Labels: feature

#3038 fix: automated login reload
  src/app/shared/services/auth/providers/firebase.auth.ts
Labels: fix

#3030 chore(deps)!: upgrade capacitor to v7
  README.md
  android/app/build.template.gradle
  android/app/capacitor.build.gradle
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
  android/variables.gradle
  documentation/docs/index.md
  ios/App/App.xcodeproj/project.template.pbxproj
  ios/App/Podfile
  ios/App/Podfile.lock
  package.json
  src/app/shared/services/audio/audio.service.ts
  src/app/shared/services/notification/local-notification.service.ts
  yarn.lock
Labels: documentation, maintenance

#3057 chore: update gh action java version
  .github/workflows/reusable-android-build.yml
Labels: maintenance

#3068 feat: ios shared parent data
  package.json
  src/app/feature/shared-data/providers/firebase.ts
Labels: feature

#3017 Update Theme Generator to create two alternative colour palettes
  src/app/feature/theme/components/colour-palette/colour-palette.component.scss
  src/app/feature/theme/components/colour-palette/colour-palette.component.ts
  src/theme/themes/default.scss
  src/theme/themes/early_family_math.scss
  src/theme/themes/pfr.scss
  src/theme/themes/plh_facilitator_mx/_index.scss
  src/theme/themes/plh_facilitator_ph/_index.scss
  src/theme/themes/plh_kids_kw/_index.scss
  src/theme/themes/plh_kids_tz/_index.scss
  src/theme/themes/professional.scss
  src/theme/themes/utils/contrast-colour.scss
  src/theme/themes/utils/generate-theme.scss
Labels: feature, test - visual, test - preview
